export interface PageMetadata {
  title: string
  description: string
  keywords: string[]
  ogImage?: string
  canonical?: string
  noindex?: boolean
}

export const seoConfig = {
  siteName: 'Cerebrum Biology Academy',
  siteUrl: 'https://cerebrumbiologyacademy.com',
  defaultTitle:
    'Best NEET Biology Coaching in Delhi NCR | South Extension, Rohini, Gurugram, Faridabad | Cerebrum Academy',
  defaultDescription:
    'Top NEET biology coaching in Delhi NCR - South Extension, Rohini, Gurugram, Faridabad. Expert AIIMS faculty, 98% success rate, small batches. Best medical entrance preparation. Book free demo!',
  defaultOgImage: '/og-image.jpg',
  twitterHandle: '@CerebrumBio',
  locale: 'en_IN',
  type: 'website',
}

export const pageMetadata: Record<string, PageMetadata> = {
  home: {
    title:
      'Best NEET Biology Coaching in Delhi NCR | South Extension, Rohini, Gurugram, Faridabad | Cerebrum Academy',
    description:
      'Top NEET Biology coaching in Delhi NCR by AIIMS faculty Dr. Shekhar. 98% success rate, 67+ AIIMS selections. Book a free demo at Cerebrum Academy!',
    keywords: [
      'NEET coaching in Delhi',
      'NEET coaching Delhi NCR',
      'Best NEET coaching Delhi',
      'Biology coaching Delhi NCR',
      'NEET preparation classes Delhi',
      'Medical entrance coaching Delhi',
      'NEET coaching South Extension',
      'NEET coaching Faridabad',
      'NEET coaching Gurugram',
      'NEET coaching Gurgaon',
      'NEET coaching Rohini',
      'Biology coaching South Extension',
      'Biology coaching Rohini',
      'Biology coaching Gurugram',
      'Biology tuition Delhi',
      'NEET 2026 coaching Delhi',
      'NEET 2026 coaching Delhi',
      'Online NEET coaching Delhi',
      'Best biology teacher NEET Delhi',
      'Affordable NEET coaching Delhi NCR',
      'NEET dropper batch Delhi',
      'Small batch NEET coaching',
      'Class 11 biology coaching Delhi',
      'Class 12 biology coaching Delhi',
      'NEET mock tests Delhi',
      'NEET crash course Delhi',
      'Biology coaching institute Delhi',
      'NEET biology classes Delhi NCR',
      'Medical coaching Delhi',
      'NEET preparation Noida',
      'NEET preparation Gurgaon',
      'NEET coaching Faridabad',
      'NEET coaching Ghaziabad',
      'NEET coaching Greater Noida',
      'Biology classes East Delhi',
      'Biology classes West Delhi',
      'NEET coaching near me Delhi',
      'Best NEET institute Delhi NCR',
      'Top NEET coaching Delhi',
      'NEET biology expert Delhi',
      'Personalized NEET coaching Delhi',
    ],
    canonical: '/',
  },
  aiEducation: {
    title: 'AI-Powered NEET Biology Learning | Personalized Study Plans',
    description:
      'AI-powered NEET Biology learning with adaptive assessments and personalized study plans. Instant doubt resolution by AIIMS faculty. Try a free demo now!',
    keywords: [
      'AI biology learning',
      'personalized NEET preparation',
      'adaptive learning',
      'AI tutor',
      'intelligent assessment',
      'smart learning platform',
      'AI-powered education',
    ],
    canonical: '/ai-education-demo',
  },
  courses: {
    title: 'NEET Biology Courses Delhi NCR | Class 11, 12, Dropper Batches | Cerebrum Academy',
    description:
      'Explore NEET 2027 Biology courses at Cerebrum Academy. Integrated programs for Class 11, 12 & Droppers with AIIMS faculty. Limited seats — enroll today!',
    keywords: [
      'NEET biology courses Delhi',
      'NEET biology syllabus',
      'biology course Delhi NCR',
      'NEET curriculum',
      'Class 11 NEET course Delhi',
      'Class 12 NEET course Delhi',
      'NEET dropper course Delhi',
      'biology chapters NEET',
      'botany course Delhi',
      'zoology course Delhi',
      'NEET class 11 biology Delhi',
      'NEET class 12 biology Delhi',
      'NEET crash course Delhi NCR',
      'NEET intensive course Delhi',
      'Biology coaching classes Delhi',
    ],
    canonical: '/courses',
  },
  about: {
    title: 'About Us - Best NEET Biology Coaching Institute Delhi NCR | Cerebrum Academy',
    description:
      'Learn about Cerebrum Biology Academy — founded by Dr. Shekhar (AIIMS Delhi) in 2010. 98% success rate, 1,50,000+ students coached. Visit us today!',
    keywords: [
      'about cerebrum academy',
      'NEET coaching institute Delhi',
      'biology faculty Delhi NCR',
      'NEET teachers Delhi',
      'best coaching center Delhi',
      'NEET institute history',
      'top NEET coaching Delhi NCR',
      'AIIMS faculty Delhi',
    ],
    canonical: '/about',
  },
  contact: {
    title: 'Contact Us - NEET Coaching in Delhi NCR | Cerebrum Academy Admissions',
    description:
      'Contact Cerebrum Biology Academy for NEET coaching — call +91-88264-44334, WhatsApp, or visit our 4 Delhi NCR centers. Book a free counseling session!',
    keywords: [
      'contact NEET coaching Delhi',
      'NEET admission Delhi NCR',
      'biology coaching inquiry',
      'NEET course details Delhi',
      'coaching center address Delhi',
      'NEET institute contact',
      'book demo class Delhi',
      'NEET coaching phone number',
    ],
    canonical: '/contact',
  },
  enrollment: {
    title: 'Enroll Now - NEET Biology Coaching Delhi NCR | Cerebrum Academy Admission',
    description:
      'Enroll in NEET Biology coaching at Cerebrum Academy, Delhi NCR. Fees from Rs 45,000 with EMI, AIIMS faculty, 98% success rate. Limited seats — enroll now!',
    keywords: [
      'NEET enrollment Delhi',
      'biology course admission Delhi NCR',
      'NEET coaching registration Delhi',
      'NEET course fees Delhi',
      'admission process NEET coaching',
      'enroll NEET Delhi',
      'join NEET coaching Delhi NCR',
      'NEET batch admission',
    ],
    canonical: '/enrollment',
  },
  bookDemo: {
    title: 'Book Free NEET Demo Class 2026 | WhatsApp Instant Booking | Cerebrum Academy Delhi NCR',
    description:
      'Book a FREE NEET Biology demo class at Cerebrum Academy. Experience small 15-student batches and AIIMS faculty teaching. Instant WhatsApp confirmation!',
    keywords: [
      'book free demo NEET coaching',
      'free demo class biology Delhi',
      'NEET coaching demo Delhi NCR',
      'free trial class NEET',
      'book NEET demo class',
      'free biology class Delhi',
      'try NEET coaching free',
      'NEET demo class near me',
      'free NEET coaching trial Delhi',
      'Cerebrum Academy demo class',
    ],
    canonical: '/book-free-demo',
  },
  results: {
    title: 'NEET Results 2026 | 98% Success Rate, 680+ Selections | Cerebrum Academy Delhi NCR',
    description:
      'Cerebrum Academy NEET results: 98% qualification rate, 680+ medical college selections, AIIMS & JIPMER toppers from Delhi NCR. Book a free demo today!',
    keywords: [
      'NEET results 2026 Cerebrum',
      'NEET success stories Delhi',
      'NEET toppers Delhi NCR',
      '98 percent NEET success rate',
      'AIIMS selections Delhi coaching',
      'NEET coaching results',
      'student testimonials NEET Delhi',
      'best NEET results Delhi NCR',
      'Cerebrum Academy results',
    ],
    canonical: '/results',
  },
  pricing: {
    title: 'NEET Coaching Fees 2026 Delhi NCR | Rs 45K–1.56L | EMI Available | Cerebrum Academy',
    description:
      'NEET Biology coaching fees from Rs 45,000 at Cerebrum Academy Delhi NCR. AIIMS faculty, 15-student batches, flexible EMI options. Book a free demo today!',
    keywords: [
      'NEET course fees Delhi',
      'NEET coaching fees 2026',
      'biology coaching cost Delhi NCR',
      'affordable NEET coaching Delhi',
      'NEET coaching fees comparison',
      'NEET coaching EMI Delhi',
      'NEET fees South Extension',
      'NEET fees Rohini',
      'NEET coaching fees Noida',
      'NEET coaching fees Gurgaon',
      'Cerebrum Academy fees',
      'small batch NEET coaching fees',
    ],
    canonical: '/pricing',
  },
  resources: {
    title: 'Free NEET Biology Study Materials Delhi NCR | Notes, PDFs | Cerebrum Academy',
    description:
      'Free NEET Biology study materials — notes, PDFs, practice questions curated by AIIMS faculty at Cerebrum Academy. Best resources in Delhi NCR. Download now!',
    keywords: [
      'NEET study material Delhi',
      'biology notes free download',
      'free NEET resources Delhi NCR',
      'NEET practice questions Delhi',
      'NEET PDF notes',
      'biology study guides Delhi',
      'free NEET material',
      'NEET preparation resources Delhi',
    ],
    canonical: '/resources',
  },
  mockTests: {
    title: 'NEET Biology Mock Tests Delhi NCR | Free Practice Test Series | Cerebrum Academy',
    description:
      'Take NEET Biology mock tests — 5,000+ questions in NTA pattern with instant results and detailed analysis. Top mock test series by AIIMS faculty. Try free!',
    keywords: [
      'NEET mock tests Delhi',
      'biology test series Delhi NCR',
      'NEET practice tests Delhi',
      'NEET mock exam Delhi',
      'online NEET test Delhi',
      'free mock test NEET Delhi',
      'NEET question paper practice',
      'NEET test series 2026 Delhi',
    ],
    canonical: '/mock-tests',
  },
  testimonials: {
    title: 'NEET Results 2026 | 98% Success Rate, 680+ Selections | Cerebrum Academy Delhi NCR',
    description:
      'Read real NEET success stories at Cerebrum Academy — 67+ AIIMS selections, 98% success rate, 1,50,000+ students trained. Watch video testimonials today!',
    keywords: [
      'NEET success stories Delhi',
      'NEET toppers Delhi NCR',
      'NEET results 2026',
      'student testimonials Delhi',
      'NEET results Delhi',
      'AIIMS selections Delhi',
      'NEET coaching results Delhi NCR',
      'student reviews Delhi',
      'NEET success rate Delhi',
      'Cerebrum Academy results',
      'NEET topper interviews',
    ],
    canonical: '/results',
  },
  faculty: {
    title: 'Expert NEET Biology Faculty Delhi NCR | AIIMS Qualified Teachers | Cerebrum Academy',
    description:
      "Meet Cerebrum Academy's AIIMS-qualified NEET Biology faculty — 15+ years experience, 680+ medical selections. Led by Dr. Shekhar Singh. Book a free demo!",
    keywords: [
      'NEET faculty Delhi',
      'biology teachers Delhi NCR',
      'AIIMS faculty Delhi',
      'best NEET teachers Delhi',
      'expert biology teachers Delhi',
      'NEET coaching faculty Delhi NCR',
      'top biology faculty Delhi',
      'experienced NEET teachers Delhi',
    ],
    canonical: '/faculty',
  },
  class9Foundation: {
    title: 'Class 9 Biology Foundation Course Delhi NCR | NEET 2028-2029 | Cerebrum Academy',
    description:
      'Class 9 NEET foundation course in Delhi NCR at Cerebrum Academy. 4-year head start, 65% higher success rate with AIIMS faculty. Book a free demo today!',
    keywords: [
      'class 9 biology foundation Delhi',
      'early NEET preparation Delhi NCR',
      'foundation biology course Delhi',
      'class 9 NEET coaching Delhi',
      'biology coaching class 9 Delhi',
      'NEET 2028 preparation Delhi',
      'class 9 medical entrance Delhi NCR',
      'early bird NEET Delhi',
      'foundation course Delhi NCR',
      'class 9 biology tuition Delhi',
    ],
    canonical: '/class-9-foundation',
  },
  class10Foundation: {
    title: 'Class 10 Biology Foundation Course Delhi NCR | NEET 2027 | Cerebrum Academy',
    description:
      'Class 10 NEET foundation course in Delhi NCR — board exam prep + NEET head start. AIIMS faculty, 65% higher success rate at Cerebrum. Book a free demo!',
    keywords: [
      'class 10 NEET preparation Delhi',
      'class 10 biology foundation Delhi NCR',
      'NEET foundation batch Delhi',
      'class 10 biology coaching Delhi',
      'early bird NEET Delhi',
      'class 10 NEET course Delhi NCR',
      'board exam NEET prep Delhi',
      'class 10 medical entrance Delhi',
      'NEET 2027 preparation Delhi',
      'foundation batch Delhi NCR',
    ],
    canonical: '/class-10-foundation',
  },
  earlyNeetPrep: {
    title: 'Why Start NEET Preparation from Class 9-10? | Early NEET Coaching',
    description:
      'Why start NEET from Class 9-10? Research shows 65% higher success rate with early preparation. Compare programs at Cerebrum Academy. Book a free demo!',
    keywords: [
      'early NEET preparation',
      'when to start NEET preparation',
      'foundation course for NEET',
      'early bird NEET coaching',
      'NEET from class 9',
      'NEET preparation class 9 10',
      'early start NEET',
      'NEET foundation program',
      'best time to start NEET',
      'early NEET coaching benefits',
    ],
    canonical: '/early-neet-preparation',
  },
  neetFoundation: {
    title: 'NEET Foundation Course - Class 9 & 10 Biology Foundation Program',
    description:
      'NEET Biology foundation program for Class 9-10 at Cerebrum Academy. 65% higher success with early start, AIIMS faculty, proven approach. Enroll today!',
    keywords: [
      'NEET foundation course',
      'biology foundation program',
      'foundation batch for NEET',
      'early NEET coaching',
      'foundation classes NEET',
      'NEET preparation foundation',
      'class 9 10 NEET foundation',
      'medical entrance foundation',
      'biology foundation coaching',
      'NEET early preparation course',
    ],
    canonical: '/neet-foundation-course',
  },
  kotaVsOnline: {
    title: 'Kota vs Online NEET Coaching 2026: Complete Comparison | Save ₹2.5L',
    description:
      'Kota vs online NEET coaching: 85% vs 60% success rate, save Rs 2.5 lakh+. Data-driven analysis every parent must read. Book a free demo at Cerebrum!',
    keywords: [
      'kota vs online coaching',
      'kota online comparison',
      'NEET coaching kota vs online',
      'online coaching better than kota',
      'kota coaching cost vs online',
      'kota alternative',
      'online NEET coaching vs kota',
      'stay home beat kota',
      'kota vs home coaching',
      'is online coaching good for NEET',
      'kota coaching fees comparison',
      'online vs offline NEET coaching',
    ],
    canonical: '/compare/kota-vs-online',
  },
  class9VsClass10: {
    title: 'Class 9 vs Class 10: When to Start NEET Preparation? | 65% Higher Success',
    description:
      'Class 9 vs Class 10 NEET start: 65% higher success with early preparation. Compare timeline, stress, and results. Book a free demo at Cerebrum Academy!',
    keywords: [
      'class 9 vs class 10 neet',
      'when to start NEET preparation',
      'class 9 or class 10 for NEET',
      'best time to start NEET',
      'early NEET preparation class 9 vs 10',
      'neet preparation timeline',
      'class 9 vs 10 foundation',
      'should i start neet from class 9',
      'when to begin NEET coaching',
      'class 9 10 comparison NEET',
      'early start vs late start NEET',
      'NEET preparation age',
    ],
    canonical: '/compare/class-9-vs-class-10-foundation',
  },
  // PAN-INDIA SEO PAGES
  onlineNeetCoachingIndia: {
    title: 'Best Online NEET Coaching in India 2026 | Pan-India Live Classes | Cerebrum Academy',
    description:
      'Best online NEET coaching in India — live classes by AIIMS faculty, 98% success rate, students from 20+ states. Join Cerebrum Academy. Enroll today!',
    keywords: [
      'online neet coaching india',
      'best online neet coaching india',
      'neet online classes india',
      'neet coaching india online',
      'pan india neet coaching',
      'online neet preparation india',
      'neet live classes india',
      'india neet coaching',
      'national neet coaching',
      'online medical coaching india',
      'neet coaching all india',
      'best neet coaching online',
      'neet coaching from home',
      'neet biology online india',
    ],
    canonical: '/online-neet-coaching-india',
  },
  bestNeetCoachingIndia: {
    title: 'Best NEET Coaching in India 2026 [Compare Top 10] | 98% Success',
    description:
      'Best NEET coaching in India — compare top 10 institutes. Cerebrum Academy: AIIMS faculty, 67+ AIIMS selections, 98% success rate. Book a FREE demo!',
    keywords: [
      'best neet coaching india',
      'top neet coaching india',
      'best neet institute india',
      'neet coaching institutes india',
      'top 10 neet coaching india',
      'best biology coaching india',
      'neet coaching india ranking',
      'best neet preparation india',
      'neet 2026 coaching india',
      'neet 2026 coaching india',
      'affordable neet coaching india',
      'neet coaching fees india',
    ],
    canonical: '/best-neet-coaching-india',
  },
  neetBiologyCoachingIndia: {
    title:
      'Best NEET Biology Coaching in India | Expert Faculty | 360/360 Toppers | Cerebrum Academy',
    description:
      'Best NEET Biology coaching in India — AIIMS faculty, 360/360 Biology toppers, Zoology & Botany expert teaching. Online classes pan-India. Enroll now!',
    keywords: [
      'neet biology coaching india',
      'best biology coaching neet india',
      'biology coaching for neet india',
      'neet biology classes india',
      'biology tuition neet india',
      'zoology coaching india',
      'botany coaching india',
      'neet biology online india',
      'biology expert coaching india',
      'neet biology preparation india',
      'biology coaching institute india',
    ],
    canonical: '/neet-biology-coaching-india',
  },
  onlineMedicalCoachingIndia: {
    title: 'Online Medical Entrance Coaching India | NEET, AIIMS, JIPMER | Cerebrum Academy',
    description:
      'Online medical entrance coaching in India for NEET, AIIMS & JIPMER. AIIMS-trained faculty, 98% success rate, live classes from home. Book a free demo!',
    keywords: [
      'online medical coaching india',
      'medical entrance coaching india',
      'neet medical coaching online',
      'aiims coaching online india',
      'jipmer coaching online',
      'medical entrance online classes',
      'doctor coaching india',
      'mbbs entrance coaching india',
      'medical coaching from home india',
      'best medical coaching online',
    ],
    canonical: '/online-medical-coaching-india',
  },
  // GURUGRAM SEO PAGES
  neetCoachingGurugram: {
    title:
      'Best NEET Coaching in Gurugram 2026 | DLF, Golf Course Road, Sushant Lok | Cerebrum Academy',
    description:
      'Best NEET coaching in Gurugram — DLF, Golf Course Road, Sushant Lok, South City. AIIMS faculty, 98% success rate, small batches. Book a free demo now!',
    keywords: [
      'neet coaching gurugram',
      'neet coaching gurgaon',
      'best neet coaching gurugram',
      'neet coaching dlf gurugram',
      'neet coaching golf course road',
      'neet coaching sushant lok',
      'biology coaching gurugram',
      'neet coaching sector 56 gurugram',
      'neet coaching sector 14 gurugram',
      'neet coaching sector 43 gurugram',
      'neet coaching sector 51 gurugram',
      'neet coaching sector 57 gurugram',
      'neet coaching south city gurugram',
      'neet coaching new gurugram',
      'neet coaching dlf phase 1',
      'neet coaching dlf phase 4',
      'online neet coaching gurugram',
      'medical coaching gurugram',
      'neet preparation gurugram',
      'best biology coaching gurgaon',
      'neet classes gurugram',
      'neet institute gurugram',
      'neet tuition gurugram',
      'neet 2026 coaching gurugram',
      'neet 2026 coaching gurugram',
    ],
    canonical: '/neet-coaching-gurugram',
  },
  // COACHING HUB PAGES
  neetCoachingKaluSarai: {
    title: 'Best NEET Coaching in Kalu Sarai 2026 | Near IIT Delhi | Cerebrum Academy',
    description:
      'Best NEET coaching in Kalu Sarai near IIT Delhi. AIIMS-trained faculty, 98% success rate, small batches, near Hauz Khas Metro. Book a free demo today!',
    keywords: [
      'neet coaching kalu sarai',
      'best neet coaching kalu sarai',
      'biology coaching kalu sarai',
      'neet coaching near iit delhi',
      'neet coaching hauz khas',
      'neet coaching sarvapriya vihar',
      'neet coaching ber sarai',
      'neet coaching green park',
      'neet classes kalu sarai',
      'neet institute kalu sarai',
      'medical coaching kalu sarai',
      'neet preparation kalu sarai delhi',
      'best biology coaching kalu sarai',
      'neet 2026 coaching kalu sarai',
    ],
    canonical: '/neet-coaching-kalu-sarai',
  },
  neetCoachingRajinderNagar: {
    title:
      "Best NEET Coaching in Rajinder Nagar 2026 | India's Coaching Capital | Cerebrum Academy",
    description:
      "Best NEET coaching near Rajinder Nagar, India's famous coaching hub. AIIMS faculty, 98% success rate, near Karol Bagh Metro. Book a free demo today!",
    keywords: [
      'neet coaching rajinder nagar',
      'best neet coaching rajinder nagar',
      'biology coaching rajinder nagar',
      'neet coaching karol bagh',
      'neet coaching old rajinder nagar',
      'neet coaching new rajinder nagar',
      'neet classes rajinder nagar',
      'neet institute rajinder nagar',
      'medical coaching rajinder nagar',
      'neet preparation rajinder nagar delhi',
      'best biology coaching rajinder nagar',
      'neet 2026 coaching rajinder nagar',
    ],
    canonical: '/neet-coaching-rajinder-nagar',
  },
  neetCoachingMukherjeeNagar: {
    title:
      "Best NEET Coaching in Mukherjee Nagar 2026 | North Delhi's Coaching Hub | Cerebrum Academy",
    description:
      'Best NEET coaching in Mukherjee Nagar, North Delhi. AIIMS-trained faculty, 98% success rate, near GTB Nagar Metro, online + offline. Book a free demo!',
    keywords: [
      'neet coaching mukherjee nagar',
      'best neet coaching mukherjee nagar',
      'biology coaching mukherjee nagar',
      'neet coaching gtb nagar',
      'neet coaching hudson lane',
      'neet classes mukherjee nagar',
      'neet institute mukherjee nagar',
      'medical coaching mukherjee nagar',
      'neet preparation mukherjee nagar delhi',
      'best biology coaching mukherjee nagar',
      'neet 2026 coaching mukherjee nagar',
    ],
    canonical: '/neet-coaching-mukherjee-nagar',
  },
  neetCoachingGtbNagar: {
    title: 'Best NEET Coaching in GTB Nagar 2026 | Near Delhi University | Cerebrum Academy',
    description:
      'Best NEET coaching near GTB Nagar and Delhi University. AIIMS faculty, 98% success rate, academic environment. Online + offline. Book a free demo today!',
    keywords: [
      'neet coaching gtb nagar',
      'best neet coaching gtb nagar',
      'biology coaching gtb nagar',
      'neet coaching near delhi university',
      'neet coaching north campus',
      'neet classes gtb nagar',
      'neet institute gtb nagar',
      'medical coaching gtb nagar',
      'neet preparation gtb nagar delhi',
      'best biology coaching gtb nagar',
      'neet 2026 coaching gtb nagar',
    ],
    canonical: '/neet-coaching-gtb-nagar',
  },
  neetCoachingLajpatNagar: {
    title: 'Best NEET Coaching in Lajpat Nagar 2026 | South Delhi Hub | Cerebrum Academy',
    description:
      'Best NEET coaching in Lajpat Nagar, South Delhi. AIIMS faculty, 98% success rate, excellent metro connectivity, small batches. Book a free demo today!',
    keywords: [
      'neet coaching lajpat nagar',
      'best neet coaching lajpat nagar',
      'biology coaching lajpat nagar',
      'neet coaching defence colony',
      'neet coaching jangpura',
      'neet classes lajpat nagar',
      'neet institute lajpat nagar',
      'medical coaching lajpat nagar',
      'neet preparation lajpat nagar delhi',
      'best biology coaching lajpat nagar',
      'neet 2026 coaching lajpat nagar',
    ],
    canonical: '/neet-coaching-lajpat-nagar',
  },
  neetCoachingJanakpuri: {
    title: 'Best NEET Coaching in Janakpuri 2026 | West Delhi | Cerebrum Academy',
    description:
      'Best NEET coaching in Janakpuri, West Delhi. AIIMS-trained faculty, 98% success rate, near Janakpuri West Metro, online + offline. Book a free demo!',
    keywords: [
      'neet coaching janakpuri',
      'best neet coaching janakpuri',
      'biology coaching janakpuri',
      'neet coaching west delhi',
      'neet coaching vikaspuri',
      'neet coaching tilak nagar',
      'neet classes janakpuri',
      'neet institute janakpuri',
      'medical coaching janakpuri',
      'neet preparation janakpuri delhi',
      'best biology coaching janakpuri',
      'neet 2026 coaching janakpuri',
    ],
    canonical: '/neet-coaching-janakpuri',
  },
  // DELHI REGIONAL PAGES
  neetCoachingNorthDelhi: {
    title:
      'Best NEET Coaching in North Delhi 2026 | Rohini, Pitampura, Model Town | Cerebrum Academy',
    description:
      'Best NEET coaching in North Delhi — Rohini, Pitampura, Model Town, GTB Nagar. AIIMS faculty, 98% success rate, small batches. Book a free demo today!',
    keywords: [
      'neet coaching north delhi',
      'best neet coaching north delhi',
      'biology coaching north delhi',
      'neet coaching rohini',
      'neet coaching pitampura',
      'neet coaching model town',
      'neet coaching shalimar bagh',
      'neet classes north delhi',
      'neet institute north delhi',
      'medical coaching north delhi',
      'neet preparation north delhi',
      'best biology coaching north delhi',
      'neet 2026 coaching north delhi',
    ],
    canonical: '/neet-coaching-north-delhi',
  },
  neetCoachingEastDelhi: {
    title: 'Best NEET Coaching in East Delhi 2026 | Laxmi Nagar, Preet Vihar | Cerebrum Academy',
    description:
      'Best NEET coaching in East Delhi — Laxmi Nagar, Preet Vihar, Mayur Vihar, IP Extension. AIIMS faculty, 98% success rate. Book a free demo class today!',
    keywords: [
      'neet coaching east delhi',
      'best neet coaching east delhi',
      'biology coaching east delhi',
      'neet coaching laxmi nagar',
      'neet coaching preet vihar',
      'neet coaching mayur vihar',
      'neet coaching ip extension',
      'neet classes east delhi',
      'neet institute east delhi',
      'medical coaching east delhi',
      'neet preparation east delhi',
      'best biology coaching east delhi',
      'neet 2026 coaching east delhi',
    ],
    canonical: '/neet-coaching-east-delhi',
  },
  neetCoachingWestDelhi: {
    title: 'Best NEET Coaching in West Delhi 2026 | Dwarka, Janakpuri, Rajouri | Cerebrum Academy',
    description:
      'Best NEET coaching in West Delhi — Dwarka, Janakpuri, Rajouri Garden. AIIMS-trained faculty, 98% success rate, small batches. Book a free demo today!',
    keywords: [
      'neet coaching west delhi',
      'best neet coaching west delhi',
      'biology coaching west delhi',
      'neet coaching dwarka',
      'neet coaching janakpuri',
      'neet coaching rajouri garden',
      'neet coaching uttam nagar',
      'neet classes west delhi',
      'neet institute west delhi',
      'medical coaching west delhi',
      'neet preparation west delhi',
      'best biology coaching west delhi',
      'neet 2026 coaching west delhi',
    ],
    canonical: '/neet-coaching-west-delhi',
  },
  neetCoachingSouthDelhi: {
    title: 'Best NEET Coaching in South Delhi 2026 | Kalu Sarai, Hauz Khas, GK | Cerebrum Academy',
    description:
      'Best NEET coaching in South Delhi — Kalu Sarai, Hauz Khas, GK, Saket. AIIMS-trained faculty, 98% success rate, small batches. Book a free demo today!',
    keywords: [
      'neet coaching south delhi',
      'best neet coaching south delhi',
      'biology coaching south delhi',
      'neet coaching kalu sarai',
      'neet coaching hauz khas',
      'neet coaching greater kailash',
      'neet coaching saket',
      'neet classes south delhi',
      'neet institute south delhi',
      'medical coaching south delhi',
      'neet preparation south delhi',
      'best biology coaching south delhi',
      'neet 2026 coaching south delhi',
    ],
    canonical: '/neet-coaching-south-delhi',
  },
  // NCR CITY PAGES
  neetCoachingNoida: {
    title: 'Best NEET Coaching in Noida 2026 | Sector 18, 62, 63 | Cerebrum Academy',
    description:
      'Best NEET coaching in Noida — Sector 18, 62, 63. AIIMS-trained faculty, 98% success rate, online + offline classes at Cerebrum Academy. Book a free demo!',
    keywords: [
      'neet coaching noida',
      'best neet coaching noida',
      'biology coaching noida',
      'neet coaching sector 18 noida',
      'neet coaching sector 62 noida',
      'neet coaching sector 63 noida',
      'neet classes noida',
      'neet institute noida',
      'medical coaching noida',
      'neet preparation noida',
      'best biology coaching noida',
      'neet 2026 coaching noida',
    ],
    canonical: '/neet-coaching-noida',
  },
  neetCoachingGhaziabad: {
    title: 'Best NEET Coaching in Ghaziabad 2026 | Indirapuram, Vaishali | Cerebrum Academy',
    description:
      'Best NEET coaching in Ghaziabad — Indirapuram, Vaishali, Vasundhara. AIIMS faculty, 98% success rate, online + offline classes. Book a free demo today!',
    keywords: [
      'neet coaching ghaziabad',
      'best neet coaching ghaziabad',
      'biology coaching ghaziabad',
      'neet coaching indirapuram',
      'neet coaching vaishali',
      'neet coaching vasundhara',
      'neet classes ghaziabad',
      'neet institute ghaziabad',
      'medical coaching ghaziabad',
      'neet preparation ghaziabad',
      'best biology coaching ghaziabad',
      'neet 2026 coaching ghaziabad',
    ],
    canonical: '/neet-coaching-ghaziabad',
  },
  neetCoachingFaridabad: {
    title: 'Best NEET Coaching in Faridabad 2026 | Sector 17 | Cerebrum Academy',
    description:
      'Best NEET coaching in Faridabad — Sector 17, NIT, Ballabhgarh. AIIMS-trained faculty, 98% success rate, online + offline classes. Book a free demo now!',
    keywords: [
      'neet coaching faridabad',
      'best neet coaching faridabad',
      'biology coaching faridabad',
      'neet coaching sector 15 faridabad',
      'neet coaching nit faridabad',
      'neet coaching ballabhgarh',
      'neet classes faridabad',
      'neet institute faridabad',
      'medical coaching faridabad',
      'neet preparation faridabad',
      'best biology coaching faridabad',
      'neet 2026 coaching faridabad',
    ],
    canonical: '/neet-coaching-faridabad',
  },
  neetCoachingGurgaon: {
    title: 'Best NEET Coaching in Gurgaon 2026 | DLF, Sector 14, 56 | Cerebrum Academy',
    description:
      'Best NEET coaching in Gurgaon — DLF, Sector 14, 56, Golf Course Road. AIIMS-trained faculty, 98% success rate, small batches. Book a free demo today!',
    keywords: [
      'neet coaching gurgaon',
      'best neet coaching gurgaon',
      'biology coaching gurgaon',
      'neet coaching dlf gurgaon',
      'neet coaching sector 14 gurgaon',
      'neet coaching sector 56 gurgaon',
      'neet classes gurgaon',
      'neet institute gurgaon',
      'medical coaching gurgaon',
      'neet preparation gurgaon',
      'best biology coaching gurgaon',
      'neet 2026 coaching gurgaon',
    ],
    canonical: '/neet-coaching-gurgaon',
  },
  neetCoachingGreaterNoidaWest: {
    title: 'Best NEET Coaching in Greater Noida West 2026 | Noida Extension | Cerebrum Academy',
    description:
      'Best NEET coaching in Greater Noida West (Noida Extension). AIIMS-trained faculty, 98% success rate, online + offline classes. Book a free demo today!',
    keywords: [
      'neet coaching greater noida west',
      'best neet coaching noida extension',
      'biology coaching greater noida west',
      'neet coaching gaur city',
      'neet classes greater noida west',
      'neet institute noida extension',
      'medical coaching greater noida west',
      'neet preparation greater noida west',
      'best biology coaching noida extension',
      'neet 2026 coaching greater noida west',
    ],
    canonical: '/neet-coaching-greater-noida-west',
  },
  // TIER-1 CITY PAGES
  neetCoachingMumbai: {
    title: 'Best NEET Coaching in Mumbai 2026 | Andheri, Dadar, Thane | Cerebrum Academy',
    description:
      'Best NEET coaching in Mumbai — Andheri, Dadar, Borivali, Thane, Navi Mumbai. AIIMS faculty, 98% success rate, online classes. Book a free demo today!',
    keywords: [
      'neet coaching mumbai',
      'best neet coaching mumbai',
      'biology coaching mumbai',
      'neet coaching andheri',
      'neet coaching dadar',
      'neet coaching borivali',
      'neet coaching thane',
      'neet classes mumbai',
      'neet institute mumbai',
      'medical coaching mumbai',
      'neet preparation mumbai',
      'best biology coaching mumbai',
      'neet 2026 coaching mumbai',
      'biology tuition mumbai',
      'online biology coaching mumbai',
      'biology classes mumbai',
      'biology teacher mumbai',
      'NEET biology mumbai',
    ],
    canonical: '/neet-coaching-mumbai',
  },
  neetCoachingBangalore: {
    title: 'Best NEET Coaching in Bangalore 2026 | Koramangala, HSR, Jayanagar | Cerebrum Academy',
    description:
      'Best NEET coaching in Bangalore — Koramangala, HSR Layout, Jayanagar. AIIMS faculty, 98% success rate, online + offline. Book a free demo at Cerebrum!',
    keywords: [
      'neet coaching bangalore',
      'best neet coaching bangalore',
      'biology coaching bangalore',
      'neet coaching koramangala',
      'neet coaching hsr layout',
      'neet coaching jayanagar',
      'neet classes bangalore',
      'neet institute bangalore',
      'medical coaching bangalore',
      'neet preparation bangalore',
      'best biology coaching bangalore',
      'neet 2026 coaching bangalore',
      'biology tuition bangalore',
      'online biology coaching bangalore',
      'biology classes bangalore',
      'biology teacher bangalore',
      'NEET biology bangalore',
    ],
    canonical: '/neet-coaching-bangalore',
  },
  neetCoachingHyderabad: {
    title: 'Best NEET Coaching in Hyderabad 2026 | KPHB, Ameerpet, Dilsukhnagar | Cerebrum Academy',
    description:
      'Best NEET coaching in Hyderabad — KPHB, Ameerpet, Dilsukhnagar. AIIMS faculty, 98% success rate, online + offline classes. Book a free demo at Cerebrum!',
    keywords: [
      'neet coaching hyderabad',
      'best neet coaching hyderabad',
      'biology coaching hyderabad',
      'neet coaching kphb',
      'neet coaching ameerpet',
      'neet coaching dilsukhnagar',
      'neet classes hyderabad',
      'neet institute hyderabad',
      'medical coaching hyderabad',
      'neet preparation hyderabad',
      'best biology coaching hyderabad',
      'neet 2026 coaching hyderabad',
      'biology tuition hyderabad',
      'online biology coaching hyderabad',
      'biology classes hyderabad',
      'biology teacher hyderabad',
      'NEET biology hyderabad',
    ],
    canonical: '/neet-coaching-hyderabad',
  },
  neetCoachingChennai: {
    title: 'Best NEET Coaching in Chennai 2026 | Anna Nagar, T Nagar, Velachery | Cerebrum Academy',
    description:
      'Best NEET coaching in Chennai — Anna Nagar, T Nagar, Velachery, Tambaram. AIIMS faculty, 98% success rate, online + offline. Book a free demo today!',
    keywords: [
      'neet coaching chennai',
      'best neet coaching chennai',
      'biology coaching chennai',
      'neet coaching anna nagar',
      'neet coaching t nagar',
      'neet coaching velachery',
      'neet classes chennai',
      'neet institute chennai',
      'medical coaching chennai',
      'neet preparation chennai',
      'best biology coaching chennai',
      'neet 2026 coaching chennai',
      'biology tuition chennai',
      'online biology coaching chennai',
      'biology classes chennai',
      'biology teacher chennai',
      'NEET biology chennai',
    ],
    canonical: '/neet-coaching-chennai',
  },
  neetCoachingPune: {
    title: 'Best NEET Coaching in Pune 2026 | Kothrud, Hinjewadi, FC Road | Cerebrum Academy',
    description:
      'Best NEET coaching in Pune — Kothrud, Hinjewadi, FC Road, Deccan. AIIMS-trained faculty, 98% success rate, online + offline classes. Book a free demo!',
    keywords: [
      'neet coaching pune',
      'best neet coaching pune',
      'biology coaching pune',
      'neet coaching kothrud',
      'neet coaching hinjewadi',
      'neet coaching fc road',
      'neet classes pune',
      'neet institute pune',
      'medical coaching pune',
      'neet preparation pune',
      'best biology coaching pune',
      'neet 2026 coaching pune',
      'biology tuition pune',
      'online biology coaching pune',
      'biology classes pune',
      'biology teacher pune',
      'NEET biology pune',
    ],
    canonical: '/neet-coaching-pune',
  },
  apBiologyTutor: {
    title: 'AP Biology Tutor | Score 5 on Your AP Bio Exam | Expert Tutoring',
    description:
      'Score 5 on AP Biology with expert tutors. 90% of students score 4-5. Complete College Board curriculum, FRQ mastery, PhD-level tutors. Book a free demo!',
    keywords: [
      'ap biology tutor',
      'ap bio tutor',
      'ap biology tutoring',
      'ap bio help',
      'ap biology exam prep',
      'ap biology online tutoring',
      'college board ap biology',
      'ap biology score 5',
      'ap biology frq help',
      'ap biology test prep',
      'ap bio exam help',
      'ap biology study guide',
      'ap bio practice test',
      'ap biology course help',
      'best ap biology tutor',
      'ap biology private tutor',
      'ap bio tutoring online',
      'ap biology 1-on-1 tutoring',
    ],
    canonical: '/ap-biology-tutor',
  },
  gallery: {
    title: 'Gallery | Student Achievements, Events & Centers | Cerebrum Biology Academy',
    description:
      'Explore our Wall of Excellence — student achievements, campus life, and events at Cerebrum Biology Academy. 67+ AIIMS selections and counting. Visit us!',
    keywords: [
      'Cerebrum gallery',
      'NEET toppers photo',
      'student achievements',
      'coaching center photos',
      'student success stories',
      'event photos',
      'center tour',
      'NEET celebration',
      'biology students',
      'academy gallery',
    ],
    canonical: '/gallery',
  },
  timetable: {
    title: 'NEET Batch Timetable & Schedule | Class 11, 12, Dropper | Cerebrum Academy Delhi NCR',
    description:
      'View NEET Biology batch schedule at Cerebrum Academy — Class 11, 12, Dropper, Foundation timings across all Delhi NCR centers. Book a free demo today!',
    keywords: [
      'batch schedule',
      'NEET class timing',
      'coaching timetable',
      'batch timing Delhi',
      'class schedule NEET',
      'coaching timing',
      'class 11 timing',
      'class 12 timing',
      'dropper batch timing',
      'NEET batch schedule',
    ],
    canonical: '/timetable',
  },
}

export function generateMetadata(pageKey: string): PageMetadata {
  return (
    pageMetadata[pageKey] || {
      title: seoConfig.defaultTitle,
      description: seoConfig.defaultDescription,
      keywords: [],
      canonical: '/',
    }
  )
}

export function generatePageMetadata(pageKey: string) {
  const meta = generateMetadata(pageKey)

  return {
    title: meta.title,
    description: meta.description,
    keywords: meta.keywords,
    openGraph: {
      title: meta.title,
      description: meta.description,
      url: `${seoConfig.siteUrl}${meta.canonical}`,
      siteName: seoConfig.siteName,
      images: [
        {
          url: `${seoConfig.siteUrl}${meta.ogImage || seoConfig.defaultOgImage}`,
          width: 1200,
          height: 630,
          alt: meta.title,
        },
      ],
      locale: seoConfig.locale,
      type: 'website',
    },
    twitter: {
      card: 'summary_large_image',
      title: meta.title,
      description: meta.description,
      site: seoConfig.twitterHandle,
      images: [`${seoConfig.siteUrl}${meta.ogImage || seoConfig.defaultOgImage}`],
    },
    robots: {
      index: !meta.noindex,
      follow: !meta.noindex,
      googleBot: {
        index: !meta.noindex,
        follow: !meta.noindex,
        'max-video-preview': -1,
        'max-image-preview': 'large' as const,
        'max-snippet': -1,
      },
    },
    alternates: {
      canonical: `${seoConfig.siteUrl}${meta.canonical}`,
    },
  }
}
