#!/usr/bin/env python3
"""
Pricing Calculator for International Country Pages
Converts USD base pricing to local currencies for 10 target markets.
"""

from dataclasses import dataclass
from typing import Dict, Tuple
import json

# Base prices in USD
BASE_SMALL_GROUP_USD = 40  # per hour
BASE_ONE_ON_ONE_MIN_USD = 70  # per hour
BASE_ONE_ON_ONE_MAX_USD = 120  # per hour

@dataclass
class Currency:
    """Currency configuration for a country."""
    code: str
    symbol: str
    rate: float  # Exchange rate from USD (1 USD = X local currency)

@dataclass
class CountryPricing:
    """Pricing configuration for a country."""
    country_code: str
    country_name: str
    currency: Currency
    small_group: int
    one_on_one_min: int
    one_on_one_max: int

# Exchange rates as of January 2025 (approximate)
# Update these periodically for accuracy
CURRENCIES: Dict[str, Currency] = {
    "us": Currency("USD", "$", 1.0),
    "uk": Currency("GBP", "£", 0.79),
    "ca": Currency("CAD", "$", 1.36),
    "au": Currency("AUD", "$", 1.54),
    "sg": Currency("SGD", "$", 1.34),
    "ae": Currency("AED", "AED ", 3.67),
    "ie": Currency("EUR", "€", 0.92),
    "hk": Currency("HKD", "$", 7.79),
    "nz": Currency("NZD", "$", 1.64),
    "za": Currency("ZAR", "R", 18.20),
}

COUNTRY_NAMES: Dict[str, str] = {
    "us": "United States",
    "uk": "United Kingdom",
    "ca": "Canada",
    "au": "Australia",
    "sg": "Singapore",
    "ae": "United Arab Emirates",
    "ie": "Ireland",
    "hk": "Hong Kong",
    "nz": "New Zealand",
    "za": "South Africa",
}

def round_to_nice_number(value: float) -> int:
    """
    Round to a 'nice' pricing number.
    - Values under 100: round to nearest 5
    - Values 100-1000: round to nearest 10
    - Values over 1000: round to nearest 50
    """
    if value < 100:
        return int(round(value / 5) * 5)
    elif value < 1000:
        return int(round(value / 10) * 10)
    else:
        return int(round(value / 50) * 50)

def calculate_country_pricing(country_code: str) -> CountryPricing:
    """Calculate pricing for a specific country."""
    currency = CURRENCIES[country_code]
    country_name = COUNTRY_NAMES[country_code]

    # Convert base USD prices to local currency
    small_group = round_to_nice_number(BASE_SMALL_GROUP_USD * currency.rate)
    one_on_one_min = round_to_nice_number(BASE_ONE_ON_ONE_MIN_USD * currency.rate)
    one_on_one_max = round_to_nice_number(BASE_ONE_ON_ONE_MAX_USD * currency.rate)

    return CountryPricing(
        country_code=country_code,
        country_name=country_name,
        currency=currency,
        small_group=small_group,
        one_on_one_min=one_on_one_min,
        one_on_one_max=one_on_one_max,
    )

def calculate_all_pricing() -> Dict[str, CountryPricing]:
    """Calculate pricing for all countries."""
    return {code: calculate_country_pricing(code) for code in CURRENCIES.keys()}

def format_price(amount: int, currency: Currency) -> str:
    """Format price with currency symbol."""
    return f"{currency.symbol}{amount}"

def generate_typescript_config() -> str:
    """Generate TypeScript configuration for countries.ts"""
    all_pricing = calculate_all_pricing()

    output = """// Auto-generated by pricing-calculator.py
// Last updated: January 2025
// Base pricing: Small Group $40 USD/hr, 1-on-1 $70-120 USD/hr

export interface CountryPricing {
  smallGroup: number
  oneOnOneMin: number
  oneOnOneMax: number
}

export interface CountryCurrency {
  code: string
  symbol: string
  rate: number
}

export const COUNTRY_PRICING: Record<string, CountryPricing> = {
"""

    for code, pricing in all_pricing.items():
        output += f"""  {code}: {{
    smallGroup: {pricing.small_group},
    oneOnOneMin: {pricing.one_on_one_min},
    oneOnOneMax: {pricing.one_on_one_max},
  }},
"""

    output += """}

export const COUNTRY_CURRENCIES: Record<string, CountryCurrency> = {
"""

    for code, currency in CURRENCIES.items():
        output += f"""  {code}: {{
    code: "{currency.code}",
    symbol: "{currency.symbol}",
    rate: {currency.rate},
  }},
"""

    output += "}\n"

    return output

def print_pricing_table():
    """Print a formatted pricing table for all countries."""
    all_pricing = calculate_all_pricing()

    print("\n" + "=" * 80)
    print("INTERNATIONAL PRICING TABLE")
    print("Base: Small Group $40 USD/hr | 1-on-1 $70-120 USD/hr")
    print("=" * 80)
    print(f"{'Country':<20} {'Currency':<8} {'Small Group':<15} {'1-on-1 Range':<20}")
    print("-" * 80)

    for code, pricing in all_pricing.items():
        currency = pricing.currency
        small_group = format_price(pricing.small_group, currency)
        one_on_one = f"{format_price(pricing.one_on_one_min, currency)} - {format_price(pricing.one_on_one_max, currency)}"
        print(f"{pricing.country_name:<20} {currency.code:<8} {small_group:<15} {one_on_one:<20}")

    print("=" * 80 + "\n")

def print_json_output():
    """Print JSON output for integration."""
    all_pricing = calculate_all_pricing()

    output = {}
    for code, pricing in all_pricing.items():
        output[code] = {
            "countryName": pricing.country_name,
            "currency": {
                "code": pricing.currency.code,
                "symbol": pricing.currency.symbol,
                "rate": pricing.currency.rate,
            },
            "pricing": {
                "smallGroup": pricing.small_group,
                "oneOnOneMin": pricing.one_on_one_min,
                "oneOnOneMax": pricing.one_on_one_max,
            }
        }

    print(json.dumps(output, indent=2))

if __name__ == "__main__":
    import sys

    if len(sys.argv) > 1:
        if sys.argv[1] == "--json":
            print_json_output()
        elif sys.argv[1] == "--typescript":
            print(generate_typescript_config())
        elif sys.argv[1] == "--help":
            print("Usage: python pricing-calculator.py [--json|--typescript|--help]")
            print("  --json       Output pricing data as JSON")
            print("  --typescript Output TypeScript configuration")
            print("  (no args)    Print formatted pricing table")
        else:
            print_pricing_table()
    else:
        print_pricing_table()
        print("\nTo generate TypeScript config:")
        print("  python pricing-calculator.py --typescript > src/lib/international/pricing-generated.ts")
        print("\nTo get JSON output:")
        print("  python pricing-calculator.py --json")
