/**
 * Demo API Route - No Authentication Required
 * GET /api/counselor/leads/demo
 */

import { NextResponse } from 'next/server'

export async function GET() {
  // Mock data for demo purposes
  const mockLeads = [
    {
      id: 'lead-1',
      studentName: 'Rahul Sharma',
      email: 'rahul.sharma@example.com',
      phone: '+91 98765 43210',
      grade: 'CLASS_12',
      city: 'Delhi',
      school: 'Delhi Public School',
      stage: 'NEW_LEAD',
      priority: 'HOT',
      source: 'Website',
      interestedCourse: 'Class 12th Biology',
      followUpDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
      createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      _count: { communications: 2, tasks: 1, notes: 0 },
    },
    {
      id: 'lead-2',
      studentName: 'Priya Patel',
      email: 'priya.patel@example.com',
      phone: '+91 98765 43220',
      grade: 'CLASS_11',
      city: 'Mumbai',
      school: 'Kendriya Vidyalaya',
      stage: 'CONTACTED',
      priority: 'HOT',
      source: 'Referral',
      interestedCourse: 'Class 11th Biology',
      followUpDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
      lastContactedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      _count: { communications: 3, tasks: 2, notes: 1 },
    },
    {
      id: 'lead-3',
      studentName: 'Amit Kumar',
      email: 'amit.kumar@example.com',
      phone: '+91 98765 43230',
      grade: 'DROPPER',
      city: 'Kota',
      school: 'Allen Career Institute',
      stage: 'DEMO_SCHEDULED',
      priority: 'WARM',
      source: 'Google Ads',
      interestedCourse: 'NEET Dropper Program',
      followUpDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
      demoScheduledAt: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
      lastContactedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      _count: { communications: 4, tasks: 2, notes: 1 },
    },
    {
      id: 'lead-4',
      studentName: 'Sneha Reddy',
      email: 'sneha.reddy@example.com',
      phone: '+91 98765 43240',
      grade: 'CLASS_12',
      city: 'Hyderabad',
      school: 'Narayana IIT Academy',
      stage: 'DEMO_COMPLETED',
      priority: 'HOT',
      source: 'Facebook',
      interestedCourse: 'Class 12th Biology',
      followUpDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
      demoCompletedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      lastContactedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      _count: { communications: 5, tasks: 1, notes: 2 },
    },
    {
      id: 'lead-5',
      studentName: 'Vikram Singh',
      email: 'vikram.singh@example.com',
      phone: '+91 98765 43250',
      grade: 'CLASS_11',
      city: 'Jaipur',
      school: 'Ryan International',
      stage: 'OFFER_SENT',
      priority: 'WARM',
      source: 'Instagram',
      interestedCourse: 'Class 11th Biology',
      followUpDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
      lastContactedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
      _count: { communications: 6, tasks: 2, notes: 1 },
    },
    {
      id: 'lead-6',
      studentName: 'Ananya Gupta',
      email: 'ananya.gupta@example.com',
      phone: '+91 98765 43260',
      grade: 'CLASS_12',
      city: 'Bangalore',
      school: 'National Public School',
      stage: 'NEGOTIATING',
      priority: 'HOT',
      source: 'Website',
      interestedCourse: 'Class 12th Biology',
      followUpDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
      lastContactedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
      _count: { communications: 8, tasks: 3, notes: 2 },
    },
    {
      id: 'lead-7',
      studentName: 'Rohan Mehta',
      email: 'rohan.mehta@example.com',
      phone: '+91 98765 43270',
      grade: 'DROPPER',
      city: 'Pune',
      school: 'FIITJEE',
      stage: 'PAYMENT_PENDING',
      priority: 'URGENT',
      source: 'Referral',
      interestedCourse: 'NEET Dropper Program',
      followUpDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
      lastContactedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
      createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
      _count: { communications: 10, tasks: 4, notes: 3 },
    },
    {
      id: 'lead-8',
      studentName: 'Kavya Iyer',
      email: 'kavya.iyer@example.com',
      phone: '+91 98765 43280',
      grade: 'CLASS_12',
      city: 'Chennai',
      school: 'Padma Seshadri',
      stage: 'ENROLLED',
      priority: 'COLD',
      source: 'Website',
      interestedCourse: 'Class 12th Biology',
      enrolledAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      lastContactedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
      createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
      _count: { communications: 12, tasks: 1, notes: 4 },
    },
    {
      id: 'lead-9',
      studentName: 'Arjun Nair',
      email: 'arjun.nair@example.com',
      phone: '+91 98765 43290',
      grade: 'CLASS_11',
      city: 'Kochi',
      school: 'Rajagiri Public School',
      stage: 'ACTIVE_STUDENT',
      priority: 'COLD',
      source: 'Referral',
      interestedCourse: 'Class 11th Biology',
      enrolledAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
      lastContactedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
      _count: { communications: 15, tasks: 0, notes: 5 },
    },
    {
      id: 'lead-10',
      studentName: 'Tanvi Joshi',
      email: 'tanvi.joshi@example.com',
      phone: '+91 98765 43300',
      grade: 'CLASS_12',
      city: 'Ahmedabad',
      school: 'Zydus School',
      stage: 'NEW_LEAD',
      priority: 'WARM',
      source: 'Google Ads',
      interestedCourse: 'Class 12th Biology',
      followUpDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
      createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      _count: { communications: 1, tasks: 1, notes: 0 },
    },
    {
      id: 'lead-11',
      studentName: 'Aditya Desai',
      email: 'aditya.desai@example.com',
      phone: '+91 98765 43310',
      grade: 'DROPPER',
      city: 'Surat',
      school: 'Resonance',
      stage: 'CONTACTED',
      priority: 'HOT',
      source: 'YouTube',
      interestedCourse: 'NEET Dropper Program',
      followUpDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
      lastContactedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
      createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      _count: { communications: 2, tasks: 2, notes: 0 },
    },
    {
      id: 'lead-12',
      studentName: 'Diya Kapoor',
      email: 'diya.kapoor@example.com',
      phone: '+91 98765 43320',
      grade: 'CLASS_11',
      city: 'Chandigarh',
      school: 'DAV Public School',
      stage: 'LOST',
      priority: 'COLD',
      source: 'Facebook',
      interestedCourse: 'Class 11th Biology',
      lastContactedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
      createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
      lostReason: 'Joined another institute',
      _count: { communications: 5, tasks: 0, notes: 2 },
    },
  ]

  return NextResponse.json({
    success: true,
    data: mockLeads,
  })
}
