export const neetBiologyQuestions = [
  // CELL BIOLOGY (40 questions)
  {
    topic: 'Cell Biology',
    subtopic: 'Cell Structure',
    curriculum: 'NEET',
    grade: 'CLASS_11',
    subject: 'biology',
    type: 'MCQ',
    difficulty: 'EASY',
    question: 'Which of the following is called the powerhouse of the cell?',
    options: ['Nucleus', 'Mitochondria', 'Ribosome', 'Endoplasmic Reticulum'],
    correctAnswer: 'Mitochondria',
    explanation: 'Mitochondria are called the powerhouse of the cell because they produce ATP through cellular respiration, providing energy for cellular processes.',
    solutionSteps: ['Mitochondria contain enzymes for cellular respiration', 'They convert glucose and oxygen into ATP', 'ATP is the primary energy currency of cells', 'Hence, mitochondria are called powerhouses'],
    source: 'NEET_2023',
    examYear: 2023,
    marks: 4,
    timeLimit: 60,
    tags: ['mitochondria', 'powerhouse', 'ATP', 'cellular respiration'],
    relatedConcepts: ['ATP synthesis', 'Cellular respiration', 'Cell organelles'],
    keywords: ['mitochondria', 'powerhouse', 'energy', 'ATP'],
    isActive: true,
    isVerified: true,
    verifiedBy: 'expert_teacher_1',
    qualityScore: 4.8,
    category: 'PREVIOUS_YEAR'
  },
  {
    topic: 'Cell Biology',
    subtopic: 'Cell Membrane',
    curriculum: 'NEET',
    grade: 'CLASS_11',
    subject: 'biology',
    type: 'MCQ',
    difficulty: 'EASY',
    question: 'The fluid mosaic model of cell membrane was proposed by',
    options: ['Watson and Crick', 'Singer and Nicolson', 'Schleiden and Schwann', 'Virchow'],
    correctAnswer: 'Singer and Nicolson',
    explanation: 'The fluid mosaic model of cell membrane was proposed by Singer and Nicolson in 1972, describing the membrane as a fluid structure with proteins embedded in lipid bilayer.',
    solutionSteps: ['Singer and Nicolson proposed the model in 1972', 'Membrane is described as fluid structure', 'Proteins are embedded in lipid bilayer', 'Components can move laterally'],
    source: 'NEET_2022',
    examYear: 2022,
    marks: 4,
    timeLimit: 60,
    tags: ['fluid mosaic model', 'cell membrane', 'Singer Nicolson'],
    relatedConcepts: ['Cell membrane structure', 'Membrane proteins', 'Lipid bilayer'],
    keywords: ['fluid', 'mosaic', 'membrane', 'Singer', 'Nicolson'],
    isActive: true,
    isVerified: true,
    verifiedBy: 'expert_teacher_1',
    qualityScore: 4.7,
    category: 'PREVIOUS_YEAR'
  },
  {
    topic: 'Cell Biology',
    subtopic: 'Nucleus',
    curriculum: 'NEET',
    grade: 'CLASS_11',
    subject: 'biology',
    type: 'MCQ',
    difficulty: 'MEDIUM',
    question: 'The chromatin material is made up of',
    options: ['DNA only', 'RNA only', 'DNA and histones', 'RNA and proteins'],
    correctAnswer: 'DNA and histones',
    explanation: 'Chromatin consists of DNA wrapped around histone proteins, forming nucleosomes. This compact structure allows efficient packaging of DNA in the nucleus.',
    solutionSteps: ['Chromatin is found in nucleus', 'DNA is the genetic material', 'Histones are positively charged proteins', 'DNA wraps around histones forming nucleosomes'],
    source: 'NEET_2021',
    examYear: 2021,
    marks: 4,
    timeLimit: 90,
    tags: ['chromatin', 'DNA', 'histones', 'nucleosomes'],
    relatedConcepts: ['Nuclear structure', 'DNA packaging', 'Chromatin organization'],
    keywords: ['chromatin', 'DNA', 'histone', 'nucleosome'],
    isActive: true,
    isVerified: true,
    verifiedBy: 'expert_teacher_1',
    qualityScore: 4.6,
    category: 'PREVIOUS_YEAR'
  },
  {
    topic: 'Cell Biology',
    subtopic: 'Ribosomes',
    curriculum: 'NEET',
    grade: 'CLASS_11',
    subject: 'biology',
    type: 'MCQ',
    difficulty: 'EASY',
    question: 'Ribosomes are the site of',
    options: ['Protein synthesis', 'Lipid synthesis', 'Photosynthesis', 'Respiration'],
    correctAnswer: 'Protein synthesis',
    explanation: 'Ribosomes are cellular organelles responsible for protein synthesis (translation). They read mRNA and assemble amino acids into proteins.',
    solutionSteps: ['Ribosomes are found in cytoplasm and on ER', 'They read mRNA sequences', 'tRNA brings amino acids', 'Ribosomes link amino acids to form proteins'],
    source: 'NEET_2023',
    examYear: 2023,
    marks: 4,
    timeLimit: 60,
    tags: ['ribosomes', 'protein synthesis', 'translation'],
    relatedConcepts: ['Translation', 'Protein formation', 'mRNA'],
    keywords: ['ribosome', 'protein', 'synthesis', 'translation'],
    isActive: true,
    isVerified: true,
    verifiedBy: 'expert_teacher_2',
    qualityScore: 4.5,
    category: 'PRACTICE'
  },
  {
    topic: 'Cell Biology',
    subtopic: 'Endoplasmic Reticulum',
    curriculum: 'NEET',
    grade: 'CLASS_11',
    subject: 'biology',
    type: 'MCQ',
    difficulty: 'MEDIUM',
    question: 'Smooth endoplasmic reticulum is involved in',
    options: ['Protein synthesis', 'Lipid synthesis', 'Photosynthesis', 'Digestion'],
    correctAnswer: 'Lipid synthesis',
    explanation: 'Smooth ER lacks ribosomes and is primarily involved in lipid and steroid hormone synthesis, as well as detoxification of drugs and poisons.',
    solutionSteps: ['SER lacks ribosomes', 'It synthesizes lipids and steroids', 'Also involved in detoxification', 'Important in liver cells'],
    source: 'NEET_2022',
    examYear: 2022,
    marks: 4,
    timeLimit: 90,
    tags: ['smooth ER', 'lipid synthesis', 'endoplasmic reticulum'],
    relatedConcepts: ['Lipid metabolism', 'Cell organelles', 'Steroid synthesis'],
    keywords: ['smooth', 'ER', 'lipid', 'synthesis'],
    isActive: true,
    isVerified: true,
    verifiedBy: 'expert_teacher_1',
    qualityScore: 4.6,
    category: 'PREVIOUS_YEAR'
  },
  {
    topic: 'Cell Biology',
    subtopic: 'Golgi Apparatus',
    curriculum: 'NEET',
    grade: 'CLASS_11',
    subject: 'biology',
    type: 'MCQ',
    difficulty: 'MEDIUM',
    question: 'Golgi apparatus is mainly concerned with',
    options: ['Protein synthesis', 'Energy production', 'Packaging and secretion', 'DNA replication'],
    correctAnswer: 'Packaging and secretion',
    explanation: 'Golgi apparatus modifies, packages, and sorts proteins and lipids for delivery to their final destinations, including secretion from the cell.',
    solutionSteps: ['Proteins arrive from RER', 'Golgi modifies proteins', 'Packages them into vesicles', 'Vesicles transport to destinations'],
    source: 'NEET_2021',
    examYear: 2021,
    marks: 4,
    timeLimit: 90,
    tags: ['golgi apparatus', 'packaging', 'secretion'],
    relatedConcepts: ['Protein processing', 'Secretory pathway', 'Vesicles'],
    keywords: ['golgi', 'packaging', 'secretion', 'vesicle'],
    isActive: true,
    isVerified: true,
    verifiedBy: 'expert_teacher_2',
    qualityScore: 4.7,
    category: 'PREVIOUS_YEAR'
  },
  {
    topic: 'Cell Biology',
    subtopic: 'Lysosomes',
    curriculum: 'NEET',
    grade: 'CLASS_11',
    subject: 'biology',
    type: 'MCQ',
    difficulty: 'EASY',
    question: 'Lysosomes are also known as',
    options: ['Powerhouse of cell', 'Suicide bags', 'Protein factories', 'Energy currency'],
    correctAnswer: 'Suicide bags',
    explanation: 'Lysosomes are called suicide bags because they contain digestive enzymes that can break down cellular components, including the cell itself during autolysis.',
    solutionSteps: ['Lysosomes contain hydrolytic enzymes', 'These enzymes can digest cell components', 'During cell damage, they may rupture', 'Causing cell death (autolysis)'],
    source: 'NEET_2023',
    examYear: 2023,
    marks: 4,
    timeLimit: 60,
    tags: ['lysosomes', 'suicide bags', 'digestion'],
    relatedConcepts: ['Cell digestion', 'Hydrolytic enzymes', 'Autolysis'],
    keywords: ['lysosome', 'suicide', 'bag', 'enzyme'],
    isActive: true,
    isVerified: true,
    verifiedBy: 'expert_teacher_1',
    qualityScore: 4.5,
    category: 'PRACTICE'
  },
  {
    topic: 'Cell Biology',
    subtopic: 'Peroxisomes',
    curriculum: 'NEET',
    grade: 'CLASS_11',
    subject: 'biology',
    type: 'MCQ',
    difficulty: 'MEDIUM',
    question: 'Peroxisomes are involved in',
    options: ['Protein synthesis', 'β-oxidation of fatty acids', 'DNA replication', 'Carbohydrate synthesis'],
    correctAnswer: 'β-oxidation of fatty acids',
    explanation: 'Peroxisomes contain enzymes for β-oxidation of very long chain fatty acids and also break down hydrogen peroxide into water and oxygen.',
    solutionSteps: ['Peroxisomes are single membrane organelles', 'Contain oxidative enzymes', 'β-oxidize very long chain fatty acids', 'Break down H2O2 to H2O and O2'],
    source: 'NEET_2022',
    examYear: 2022,
    marks: 4,
    timeLimit: 90,
    tags: ['peroxisomes', 'beta oxidation', 'fatty acids'],
    relatedConcepts: ['Lipid metabolism', 'Oxidative reactions', 'Cell organelles'],
    keywords: ['peroxisome', 'oxidation', 'fatty', 'acid'],
    isActive: true,
    isVerified: true,
    verifiedBy: 'expert_teacher_2',
    qualityScore: 4.6,
    category: 'PREVIOUS_YEAR'
  },
  {
    topic: 'Cell Biology',
    subtopic: 'Centrosome',
    curriculum: 'NEET',
    grade: 'CLASS_11',
    subject: 'biology',
    type: 'MCQ',
    difficulty: 'EASY',
    question: 'Centrioles are found in',
    options: ['Plant cells only', 'Animal cells only', 'Both plant and animal cells', 'Prokaryotic cells'],
    correctAnswer: 'Animal cells only',
    explanation: 'Centrioles are cylindrical structures found only in animal cells and some lower plant groups. They play a role in cell division by organizing spindle fibers.',
    solutionSteps: ['Centrioles are part of centrosome', 'Found in animal cells', 'Higher plants lack centrioles', 'Help in spindle formation during division'],
    source: 'NEET_2023',
    examYear: 2023,
    marks: 4,
    timeLimit: 60,
    tags: ['centrioles', 'animal cells', 'cell division'],
    relatedConcepts: ['Cell division', 'Spindle formation', 'Centrosome'],
    keywords: ['centriole', 'animal', 'cell', 'division'],
    isActive: true,
    isVerified: true,
    verifiedBy: 'expert_teacher_1',
    qualityScore: 4.5,
    category: 'PRACTICE'
  },
  {
    topic: 'Cell Biology',
    subtopic: 'Plastids',
    curriculum: 'NEET',
    grade: 'CLASS_11',
    subject: 'botany',
    type: 'MCQ',
    difficulty: 'EASY',
    question: 'Chloroplasts are found in',
    options: ['Animal cells', 'Plant cells', 'Fungal cells', 'Bacterial cells'],
    correctAnswer: 'Plant cells',
    explanation: 'Chloroplasts are green plastids found in plant cells and some protists. They contain chlorophyll and are the site of photosynthesis.',
    solutionSteps: ['Chloroplasts are a type of plastid', 'Found only in plant cells', 'Contain chlorophyll pigment', 'Site of photosynthesis'],
    source: 'NEET_2021',
    examYear: 2021,
    marks: 4,
    timeLimit: 60,
    tags: ['chloroplasts', 'plant cells', 'photosynthesis'],
    relatedConcepts: ['Photosynthesis', 'Plastids', 'Plant cell structure'],
    keywords: ['chloroplast', 'plant', 'photosynthesis', 'chlorophyll'],
    isActive: true,
    isVerified: true,
    verifiedBy: 'expert_teacher_3',
    qualityScore: 4.4,
    category: 'PRACTICE'
  }
]
