/**
 * Static SEO Page Slugs - Memory Efficient
 *
 * This file contains a pre-generated list of ALL SEO landing page slugs.
 * It is used by sitemap.ts to avoid loading 14 large content files (650KB+) into memory.
 *
 * MAINTENANCE:
 * - This file is AUTO-GENERATED by scripts/generate-seo-slugs.js
 * - DO NOT edit manually (except initial setup)
 * - Run `npm run generate:seo-slugs` after adding/removing SEO pages
 * - Last updated: 2025-12-25
 * - Total pages: 118
 *
 * @see scripts/generate-seo-slugs.js
 */

/**
 * All SEO landing page slugs organized by category
 */
export const SEO_PAGE_SLUGS = {
  class9: [
    'class-9-biology-tuition-online',
    'neet-foundation-class-9',
    'online-biology-classes-class-9',
    'class-9-science-tuition-neet',
  ],
  class10: [
    'class-10-biology-tuition-online',
    'neet-foundation-class-10',
    'online-biology-classes-class-10',
    'class-10-board-neet-coaching',
  ],
  class11: [
    'neet-biology-coaching-class-11',
    'class-11-biology-tuition-online',
    'online-biology-classes-class-11',
    'best-biology-tutor-class-11',
    'class-11-neet-preparation-online',
    'ncert-biology-class-11-tuition',
  ],
  class12: [
    'neet-biology-coaching-class-12',
    'class-12-biology-tuition-online',
    'online-biology-classes-class-12',
    'best-biology-tutor-class-12',
    'neet-2025-biology-coaching',
    'board-neet-biology-class-12',
  ],
  dropper: [
    'neet-dropper-batch-online',
    'neet-repeater-course-2025',
    'neet-dropper-biology-coaching',
    'best-coaching-neet-droppers',
    'one-year-neet-dropper-course',
  ],
  universal: [
    'online-biology-tuition-india',
    'neet-biology-online-coaching',
    'best-biology-teacher-neet',
    '1-on-1-biology-tuition-neet',
    'live-biology-classes-neet',
  ],
  ncert: [
    'ncert-biology-class-11',
    'ncert-biology-class-12',
    'ncert-fingertips-biology',
    'ncert-exemplar-biology',
    'ncert-biology-notes-class-11',
    'ncert-biology-notes-class-12',
    'ncert-biology-solutions',
    'ncert-punch-biology',
  ],
  topics: [
    'cell-biology-tuition',
    'molecular-biology-tuition',
    'genetics-biology-tuition',
    'evolution-class-12',
    'biodiversity-conservation-class-12',
    'animal-tissues-class-9',
    'plant-physiology-class-11',
    'living-world-ncert',
    'dna-biology-tuition',
    'botany-zoology-tuition',
    'ecology-biology-tuition',
    'human-physiology-tuition',
    'biomolecules-class-11',
    'plant-kingdom-class-11',
    'animal-kingdom-class-11',
  ],
  international: [
    'gcse-biology-tuition',
    'gcse-biology-tutor-online',
    'igcse-biology-tuition',
    'igcse-biology-tutor',
    'ib-biology-tuition',
    'ib-biology-tutor-online',
    'a-level-biology-tutor',
    'a-level-biology-tuition',
    'ap-biology-tutor',
    'international-biology-tutor',
  ],
  neetGuide: [
    'neet-syllabus-2025',
    'neet-eligibility-criteria',
    'neet-exam-pattern-2025',
    'neet-counselling-guide',
    'neet-biology-syllabus-2025',
    'neet-botany-syllabus',
    'neet-zoology-syllabus',
    'neet-preparation-guide',
    'neet-exam-details',
    'neet-registration-guide',
    'neet-result-analysis',
    'neet-official-resources',
    'neet-syllabus-2026',
    'neet-eligibility-2026',
    'neet-exam-date-2026',
    'neet-result-2026',
    'neet-application-form-2026',
  ],
  resources: [
    'neet-biology-notes-pdf',
    'neet-biology-pyq-chapter-wise',
    'neet-biology-mcq-practice',
    'neet-mock-test-free',
    'neet-biology-important-questions',
    'ncert-based-neet-questions',
    'neet-biology-revision-notes',
    'neet-biology-diagrams',
    'neet-biology-formulas',
    'neet-biology-chapter-weightage',
  ],
  chapterNotes: [
    'genetics-notes-neet',
    'human-physiology-notes-neet',
    'ecology-notes-neet',
    'cell-biology-notes-neet',
    'plant-physiology-notes-neet',
    'reproduction-notes-neet',
    'evolution-notes-neet',
    'biotechnology-notes-neet',
    'biodiversity-notes-neet',
    'animal-kingdom-notes-neet',
    'plant-kingdom-notes-neet',
    'biomolecules-notes-neet',
    'morphology-flowering-plants-notes-neet',
    'anatomy-flowering-plants-notes-neet',
    'structural-organisation-animals-notes-neet',
    'biological-classification-notes-neet',
  ],
  crashCourse: [
    'neet-biology-crash-course',
    'neet-biology-45-day-course',
    'neet-biology-90-day-course',
    'neet-biology-6-month-course',
    'neet-biology-1-year-course',
    'neet-biology-weekend-batch',
  ],
  comparison: [
    'online-vs-offline-neet-coaching',
    'best-neet-biology-coaching-india',
    'why-choose-cerebrum-academy',
    'neet-coaching-fees-comparison',
    'neet-coaching-success-rate-comparison',
    'should-i-join-neet-coaching',
  ],
} as const

/**
 * Flattened array of all SEO page slugs
 * Use this for sitemap generation and slug validation
 */
export const ALL_SEO_SLUGS: readonly string[] = [
  ...SEO_PAGE_SLUGS.class9,
  ...SEO_PAGE_SLUGS.class10,
  ...SEO_PAGE_SLUGS.class11,
  ...SEO_PAGE_SLUGS.class12,
  ...SEO_PAGE_SLUGS.dropper,
  ...SEO_PAGE_SLUGS.universal,
  ...SEO_PAGE_SLUGS.ncert,
  ...SEO_PAGE_SLUGS.topics,
  ...SEO_PAGE_SLUGS.international,
  ...SEO_PAGE_SLUGS.neetGuide,
  ...SEO_PAGE_SLUGS.resources,
  ...SEO_PAGE_SLUGS.chapterNotes,
  ...SEO_PAGE_SLUGS.crashCourse,
  ...SEO_PAGE_SLUGS.comparison,
] as const

/**
 * Get all SEO page slugs for sitemap generation
 * This function replaces getAllSEOSlugs() from index.ts
 */
export function getAllSEOSlugs(): string[] {
  return [...ALL_SEO_SLUGS]
}

/**
 * Get slugs by category
 */
export function getSEOSlugsByCategory(
  category: keyof typeof SEO_PAGE_SLUGS
): readonly string[] {
  return SEO_PAGE_SLUGS[category]
}

/**
 * Check if a slug is a valid SEO page
 */
export function isValidSEOSlug(slug: string): boolean {
  return ALL_SEO_SLUGS.includes(slug as any)
}

/**
 * Get total count of SEO pages
 */
export function getSEOPageCount(): number {
  return ALL_SEO_SLUGS.length
}

/**
 * Metadata about the slugs
 */
export const SEO_SLUGS_METADATA = {
  totalCount: 118,
  lastGenerated: '2025-12-25',
  categories: [
    'class9',
    'class10',
    'class11',
    'class12',
    'dropper',
    'universal',
    'ncert',
    'topics',
    'international',
    'neetGuide',
    'resources',
    'chapterNotes',
    'crashCourse',
    'comparison',
  ],
  categoryCounts: {
    class9: 4,
    class10: 4,
    class11: 6,
    class12: 6,
    dropper: 5,
    universal: 5,
    ncert: 8,
    topics: 15,
    international: 10,
    neetGuide: 17,
    resources: 10,
    chapterNotes: 16,
    crashCourse: 6,
    comparison: 6,
  },
} as const
