import { InteractiveDiagramData } from '@/types/interactive-diagram'

export const krebsCycleDiagram: InteractiveDiagramData = {
  type: 'cycle',
  title: 'Krebs Cycle (TCA Cycle / Citric Acid Cycle)',
  subtitle: 'Occurs in the mitochondrial matrix | Class 12 - Respiration in Plants',
  nodes: [
    {
      id: 'acetyl-coa',
      label: 'Acetyl CoA',
      description:
        'Acetyl CoA (2C) enters the cycle from pyruvate oxidation (link reaction). It is the starting substrate that combines with oxaloacetate to form citrate.',
      style: 'highlight',
      color: '#E65100',
      position: { x: 0.5, y: 0 },
    },
    {
      id: 'citrate',
      label: 'Citrate (6C)',
      description:
        'Citric acid (6C) is formed by condensation of Acetyl CoA (2C) with Oxaloacetate (4C). This reaction is catalyzed by citrate synthase. The cycle is named after this molecule.',
      style: 'primary',
      color: '#1565C0',
      position: { x: 0.85, y: 0.25 },
    },
    {
      id: 'isocitrate',
      label: 'Isocitrate (6C)',
      description:
        'Isocitrate (6C) is formed by isomerization of citrate. This is catalyzed by aconitase enzyme. It undergoes the first oxidative decarboxylation next.',
      style: 'secondary',
      color: '#1976D2',
      position: { x: 1, y: 0.5 },
    },
    {
      id: 'alpha-kg',
      label: '\u03B1-Ketoglutarate (5C)',
      description:
        '\u03B1-Ketoglutarate (5C) is formed by oxidative decarboxylation of isocitrate. One CO\u2082 is released and one NADH is produced. Catalyzed by isocitrate dehydrogenase.',
      style: 'primary',
      color: '#7B1FA2',
      position: { x: 0.85, y: 0.75 },
    },
    {
      id: 'succinyl-coa',
      label: 'Succinyl CoA (4C)',
      description:
        'Succinyl CoA (4C) is formed by the second oxidative decarboxylation. One more CO\u2082 is released and one NADH is produced. Catalyzed by \u03B1-ketoglutarate dehydrogenase complex.',
      style: 'primary',
      color: '#C62828',
      position: { x: 0.5, y: 1 },
    },
    {
      id: 'succinate',
      label: 'Succinate (4C)',
      description:
        'Succinate (4C) is formed from Succinyl CoA. This step produces one GTP (equivalent to ATP) by substrate-level phosphorylation. Catalyzed by succinyl CoA synthetase.',
      style: 'success',
      color: '#2E7D32',
      position: { x: 0.15, y: 0.75 },
    },
    {
      id: 'fumarate',
      label: 'Fumarate (4C)',
      description:
        'Fumarate (4C) is formed by oxidation of succinate. One FADH\u2082 is produced in this step. Catalyzed by succinate dehydrogenase (the only enzyme embedded in inner mitochondrial membrane).',
      style: 'secondary',
      color: '#00695C',
      position: { x: 0, y: 0.5 },
    },
    {
      id: 'malate',
      label: 'Malate (4C)',
      description:
        'Malate (4C) is formed by hydration of fumarate (addition of water). Catalyzed by fumarase enzyme.',
      style: 'secondary',
      color: '#4527A0',
      position: { x: 0.15, y: 0.25 },
    },
    {
      id: 'oaa',
      label: 'Oxaloacetate (4C)',
      description:
        'Oxaloacetate (OAA, 4C) is regenerated by oxidation of malate. One NADH is produced. OAA then combines with new Acetyl CoA to restart the cycle. This is why the cycle is self-sustaining.',
      style: 'highlight',
      color: '#E65100',
      position: { x: 0.5, y: 0 },
    },
  ],
  edges: [
    { from: 'acetyl-coa', to: 'citrate', label: 'Citrate synthase', type: 'arrow' },
    { from: 'citrate', to: 'isocitrate', label: 'Aconitase', type: 'arrow' },
    {
      from: 'isocitrate',
      to: 'alpha-kg',
      label: 'CO\u2082 + NADH',
      type: 'arrow',
      color: '#7B1FA2',
    },
    {
      from: 'alpha-kg',
      to: 'succinyl-coa',
      label: 'CO\u2082 + NADH',
      type: 'arrow',
      color: '#C62828',
    },
    { from: 'succinyl-coa', to: 'succinate', label: 'GTP', type: 'arrow', color: '#2E7D32' },
    { from: 'succinate', to: 'fumarate', label: 'FADH\u2082', type: 'arrow', color: '#00695C' },
    { from: 'fumarate', to: 'malate', label: 'H\u2082O', type: 'arrow' },
    { from: 'malate', to: 'oaa', label: 'NADH', type: 'arrow', color: '#4527A0' },
    { from: 'oaa', to: 'acetyl-coa', label: 'Cycle restarts', type: 'dashed' },
  ],
  annotations: [
    { text: 'Mitochondrial Matrix', position: { x: 0.5, y: 0.48 }, fontSize: 12 },
    {
      text: 'Net yield per cycle: 3 NADH + 1 FADH\u2082 + 1 GTP + 2 CO\u2082',
      position: { x: 0.5, y: 0.54 },
      fontSize: 10,
    },
  ],
  steps: [
    {
      stepNumber: 1,
      highlightNodes: ['acetyl-coa', 'oaa', 'citrate'],
      highlightEdges: ['acetyl-coa->citrate'],
      explanation:
        'Step 1: Acetyl CoA (2C) from pyruvate oxidation enters the cycle and condenses with Oxaloacetate (4C) to form Citrate (6C). This is catalyzed by citrate synthase. The CoA is released.',
    },
    {
      stepNumber: 2,
      highlightNodes: ['citrate', 'isocitrate'],
      highlightEdges: ['citrate->isocitrate'],
      explanation:
        'Step 2: Citrate is isomerized to Isocitrate by the enzyme aconitase. This is a reversible rearrangement reaction.',
    },
    {
      stepNumber: 3,
      highlightNodes: ['isocitrate', 'alpha-kg'],
      highlightEdges: ['isocitrate->alpha-kg'],
      explanation:
        'Step 3: First oxidative decarboxylation \u2014 Isocitrate (6C) loses one CO\u2082 to form \u03B1-Ketoglutarate (5C). One NADH is produced. Catalyzed by isocitrate dehydrogenase (rate-limiting step).',
    },
    {
      stepNumber: 4,
      highlightNodes: ['alpha-kg', 'succinyl-coa'],
      highlightEdges: ['alpha-kg->succinyl-coa'],
      explanation:
        'Step 4: Second oxidative decarboxylation \u2014 \u03B1-Ketoglutarate (5C) loses one CO\u2082 to form Succinyl CoA (4C). One more NADH is produced. Catalyzed by \u03B1-ketoglutarate dehydrogenase complex.',
    },
    {
      stepNumber: 5,
      highlightNodes: ['succinyl-coa', 'succinate'],
      highlightEdges: ['succinyl-coa->succinate'],
      explanation:
        'Step 5: Substrate-level phosphorylation \u2014 Succinyl CoA is converted to Succinate. One GTP is produced (equivalent to 1 ATP). This is the only step that directly produces a high-energy phosphate.',
    },
    {
      stepNumber: 6,
      highlightNodes: ['succinate', 'fumarate'],
      highlightEdges: ['succinate->fumarate'],
      explanation:
        'Step 6: Succinate is oxidized to Fumarate. One FADH\u2082 is produced. Succinate dehydrogenase is the only TCA enzyme embedded in the inner mitochondrial membrane (also part of Complex II in ETC).',
    },
    {
      stepNumber: 7,
      highlightNodes: ['fumarate', 'malate'],
      highlightEdges: ['fumarate->malate'],
      explanation:
        'Step 7: Fumarate is hydrated (water added) to form Malate. Catalyzed by fumarase. This is a simple hydration reaction.',
    },
    {
      stepNumber: 8,
      highlightNodes: ['malate', 'oaa'],
      highlightEdges: ['malate->oaa'],
      explanation:
        'Step 8: Malate is oxidized to regenerate Oxaloacetate (OAA). One NADH is produced (3rd NADH of the cycle). OAA is now ready to accept a new Acetyl CoA and restart the cycle.',
    },
  ],
}

export const photosynthesisFlowchart: InteractiveDiagramData = {
  type: 'flowchart',
  title: 'Photosynthesis: Light & Dark Reactions',
  subtitle: 'Class 11 - Photosynthesis in Higher Plants',
  nodes: [
    {
      id: 'light',
      label: 'Sunlight',
      description:
        'Light energy (mainly red and blue wavelengths) is absorbed by chlorophyll and accessory pigments in the thylakoid membrane.',
      position: { x: 0.5, y: 0 },
      style: 'highlight',
      color: '#F57F17',
    },
    {
      id: 'ps2',
      label: 'Photosystem II (P680)',
      description:
        'PS II absorbs light at 680nm. Water is split here (photolysis): 2H\u2082O \u2192 4H\u207A + 4e\u207B + O\u2082. This is the source of oxygen released in photosynthesis.',
      position: { x: 0.25, y: 0.18 },
      style: 'primary',
      color: '#1565C0',
    },
    {
      id: 'ps1',
      label: 'Photosystem I (P700)',
      description:
        'PS I absorbs light at 700nm. Electrons from PS II reach here via the electron transport chain. PS I re-energizes them for NADP\u207A reduction.',
      position: { x: 0.75, y: 0.18 },
      style: 'primary',
      color: '#283593',
    },
    {
      id: 'etc',
      label: 'Electron Transport Chain',
      description:
        'Electrons pass through plastoquinone, cytochrome b6f complex, and plastocyanin. This pumps H\u207A ions into the thylakoid lumen, creating a proton gradient for ATP synthesis.',
      position: { x: 0.5, y: 0.32 },
      style: 'secondary',
      color: '#4527A0',
    },
    {
      id: 'atp-synthase',
      label: 'ATP Synthase',
      description:
        'Chemiosmosis \u2014 H\u207A ions flow through CF\u2080-CF\u2081 complex (ATP synthase) from thylakoid lumen to stroma, driving ATP synthesis. This is photophosphorylation.',
      position: { x: 0.25, y: 0.46 },
      style: 'success',
      color: '#2E7D32',
    },
    {
      id: 'nadph',
      label: 'NADPH Formation',
      description:
        'Electrons from PS I reduce NADP\u207A to NADPH using the enzyme NADP\u207A reductase (ferredoxin-NADP\u207A reductase). NADPH is the assimilatory power used in the Calvin cycle.',
      position: { x: 0.75, y: 0.46 },
      style: 'success',
      color: '#1B5E20',
    },
    {
      id: 'calvin-start',
      label: 'Calvin Cycle (Dark Reaction)',
      description:
        'Occurs in the stroma. Does NOT require light directly but needs ATP and NADPH from light reactions. Also called C3 pathway or Blackman reaction.',
      position: { x: 0.5, y: 0.62 },
      style: 'highlight',
      color: '#E65100',
    },
    {
      id: 'carbon-fix',
      label: 'Carbon Fixation (RuBisCO)',
      description:
        'CO\u2082 is fixed by RuBisCO enzyme: CO\u2082 + RuBP (5C) \u2192 2 molecules of 3-PGA (3C). RuBisCO is the most abundant enzyme on Earth.',
      position: { x: 0.25, y: 0.77 },
      style: 'primary',
      color: '#BF360C',
    },
    {
      id: 'reduction',
      label: 'Reduction Phase',
      description:
        '3-PGA is reduced to G3P (glyceraldehyde-3-phosphate) using ATP and NADPH from light reactions. This is where light energy is stored as chemical energy in sugar.',
      position: { x: 0.75, y: 0.77 },
      style: 'primary',
      color: '#4E342E',
    },
    {
      id: 'g3p',
      label: 'G3P \u2192 Glucose',
      description:
        'For every 3 CO\u2082 fixed, 6 G3P are produced. 1 G3P exits as net product (used to make glucose, sucrose, starch). 5 G3P are used to regenerate RuBP.',
      position: { x: 0.5, y: 0.92 },
      style: 'success',
      color: '#2E7D32',
    },
  ],
  edges: [
    { from: 'light', to: 'ps2', label: '680nm', type: 'arrow' },
    { from: 'light', to: 'ps1', label: '700nm', type: 'arrow' },
    { from: 'ps2', to: 'etc', label: 'e\u207B', type: 'arrow', color: '#4527A0' },
    { from: 'etc', to: 'ps1', label: 'e\u207B', type: 'arrow', color: '#4527A0' },
    { from: 'etc', to: 'atp-synthase', label: 'H\u207A gradient', type: 'arrow', color: '#2E7D32' },
    { from: 'ps1', to: 'nadph', label: 'e\u207B + NADP\u207A', type: 'arrow', color: '#1B5E20' },
    { from: 'atp-synthase', to: 'calvin-start', label: 'ATP', type: 'arrow', color: '#2E7D32' },
    { from: 'nadph', to: 'calvin-start', label: 'NADPH', type: 'arrow', color: '#1B5E20' },
    { from: 'calvin-start', to: 'carbon-fix', label: 'CO\u2082 + RuBP', type: 'arrow' },
    { from: 'carbon-fix', to: 'reduction', label: '3-PGA', type: 'arrow' },
    { from: 'reduction', to: 'g3p', label: 'G3P', type: 'arrow', color: '#2E7D32' },
  ],
  steps: [
    {
      stepNumber: 1,
      highlightNodes: ['light', 'ps2', 'ps1'],
      explanation:
        'Light Absorption: Sunlight is absorbed by PS II (P680) and PS I (P700) in the thylakoid membrane. Chlorophyll a is the primary pigment; accessory pigments (chlorophyll b, carotenoids) broaden the absorption spectrum.',
    },
    {
      stepNumber: 2,
      highlightNodes: ['ps2', 'etc'],
      explanation:
        'Photolysis & Electron Transport: PS II splits water (2H\u2082O \u2192 O\u2082 + 4H\u207A + 4e\u207B). Electrons travel through the ETC (plastoquinone \u2192 cytochrome b6f \u2192 plastocyanin), pumping H\u207A into the thylakoid lumen.',
    },
    {
      stepNumber: 3,
      highlightNodes: ['etc', 'atp-synthase'],
      explanation:
        'Photophosphorylation: The H\u207A gradient drives ATP synthesis through ATP synthase (chemiosmosis). In non-cyclic photophosphorylation, both ATP and NADPH are produced.',
    },
    {
      stepNumber: 4,
      highlightNodes: ['ps1', 'nadph'],
      explanation:
        'NADPH Formation: PS I re-energizes electrons. Ferredoxin passes them to NADP\u207A reductase, reducing NADP\u207A + H\u207A to NADPH. ATP and NADPH together are called "assimilatory power".',
    },
    {
      stepNumber: 5,
      highlightNodes: ['calvin-start', 'carbon-fix'],
      explanation:
        'Carbon Fixation (Calvin Cycle Step 1): CO\u2082 is fixed by RuBisCO. RuBP (5C) + CO\u2082 \u2192 unstable 6C intermediate \u2192 2 molecules of 3-PGA (3C). 3 CO\u2082 are fixed per turn.',
    },
    {
      stepNumber: 6,
      highlightNodes: ['carbon-fix', 'reduction', 'g3p'],
      explanation:
        'Reduction & Sugar Output: 3-PGA is reduced to G3P using ATP + NADPH. For 3 CO\u2082: 6 G3P formed, 1 exits as net gain (makes glucose). 5 G3P regenerate 3 RuBP (uses 3 ATP). Overall: 3CO\u2082 + 9ATP + 6NADPH \u2192 1 G3P.',
    },
  ],
}

export const mitosisVsMeiosisComparison = {
  type: 'comparison' as const,
  title: 'Mitosis vs Meiosis',
  subtitle: 'Class 11 - Cell Cycle and Cell Division',
  left: {
    title: 'Mitosis',
    nodes: [
      {
        id: 'm-interphase',
        label: 'Interphase (G1, S, G2)',
        description:
          'DNA replicates once. Cell grows and prepares for division. 2n chromosomes become 2n replicated chromosomes.',
        position: { x: 0.5, y: 0.08 },
        style: 'primary' as const,
        color: '#1565C0',
      },
      {
        id: 'm-prophase',
        label: 'Prophase',
        description:
          'Chromatin condenses into chromosomes. Each chromosome has 2 sister chromatids joined at centromere. Spindle begins to form.',
        position: { x: 0.5, y: 0.25 },
        style: 'primary' as const,
        color: '#1976D2',
      },
      {
        id: 'm-metaphase',
        label: 'Metaphase',
        description:
          'Chromosomes align at the metaphase plate (equator). Spindle fibers attach to kinetochores at centromeres.',
        position: { x: 0.5, y: 0.42 },
        style: 'primary' as const,
        color: '#1E88E5',
      },
      {
        id: 'm-anaphase',
        label: 'Anaphase',
        description:
          'Sister chromatids separate and move to opposite poles. Centromeres split. The shortest phase of mitosis.',
        position: { x: 0.5, y: 0.59 },
        style: 'primary' as const,
        color: '#42A5F5',
      },
      {
        id: 'm-telophase',
        label: 'Telophase & Cytokinesis',
        description:
          'Nuclear envelope reforms. Chromosomes decondense. Cytokinesis divides cytoplasm. Result: 2 identical diploid (2n) daughter cells.',
        position: { x: 0.5, y: 0.76 },
        style: 'success' as const,
        color: '#2E7D32',
      },
      {
        id: 'm-result',
        label: '2 Diploid Cells (2n)',
        description:
          'Mitosis produces 2 genetically identical daughter cells, each with the same chromosome number as the parent cell (2n).',
        position: { x: 0.5, y: 0.93 },
        style: 'highlight' as const,
        color: '#E65100',
      },
    ],
    edges: [
      { from: 'm-interphase', to: 'm-prophase' },
      { from: 'm-prophase', to: 'm-metaphase' },
      { from: 'm-metaphase', to: 'm-anaphase' },
      { from: 'm-anaphase', to: 'm-telophase' },
      { from: 'm-telophase', to: 'm-result' },
    ],
  },
  right: {
    title: 'Meiosis',
    nodes: [
      {
        id: 'me-interphase',
        label: 'Interphase (G1, S, G2)',
        description:
          'DNA replicates once (same as mitosis). The key difference happens during division, not interphase.',
        position: { x: 0.5, y: 0.08 },
        style: 'primary' as const,
        color: '#7B1FA2',
      },
      {
        id: 'me-prophase1',
        label: 'Prophase I (Crossing Over)',
        description:
          'LONGEST phase. Homologous chromosomes pair up (synapsis) forming bivalents/tetrads. Crossing over occurs at chiasmata \u2014 this creates genetic variation.',
        position: { x: 0.5, y: 0.22 },
        style: 'highlight' as const,
        color: '#6A1B9A',
      },
      {
        id: 'me-meta1',
        label: 'Metaphase I',
        description:
          'Bivalents (homologous pairs) align at metaphase plate. Random orientation of pairs = independent assortment (source of genetic variation).',
        position: { x: 0.5, y: 0.36 },
        style: 'primary' as const,
        color: '#8E24AA',
      },
      {
        id: 'me-ana1',
        label: 'Anaphase I',
        description:
          'Homologous chromosomes separate (NOT sister chromatids). Each pole gets one chromosome from each homologous pair. Chromosome number is halved here.',
        position: { x: 0.5, y: 0.5 },
        style: 'danger' as const,
        color: '#C62828',
      },
      {
        id: 'me-division2',
        label: 'Meiosis II (like Mitosis)',
        description:
          'Sister chromatids separate in the second division (similar to mitosis). No further DNA replication occurs between Meiosis I and II.',
        position: { x: 0.5, y: 0.67 },
        style: 'primary' as const,
        color: '#AD1457',
      },
      {
        id: 'me-result',
        label: '4 Haploid Cells (n)',
        description:
          'Meiosis produces 4 genetically different haploid (n) daughter cells. These become gametes (sperm/eggs). Genetic variation comes from crossing over + independent assortment.',
        position: { x: 0.5, y: 0.84 },
        style: 'highlight' as const,
        color: '#E65100',
      },
    ],
    edges: [
      { from: 'me-interphase', to: 'me-prophase1' },
      { from: 'me-prophase1', to: 'me-meta1' },
      { from: 'me-meta1', to: 'me-ana1' },
      { from: 'me-ana1', to: 'me-division2' },
      { from: 'me-division2', to: 'me-result' },
    ],
  },
  sharedFeatures: [
    'Both involve DNA replication in S phase of interphase',
    'Both have prophase, metaphase, anaphase, and telophase stages',
    'Both require spindle apparatus for chromosome movement',
    'Both involve condensation of chromatin into chromosomes',
  ],
  differences: [
    { left: 'One division', right: 'Two divisions (Meiosis I + II)' },
    { left: '2 daughter cells', right: '4 daughter cells' },
    { left: 'Diploid (2n) daughters', right: 'Haploid (n) daughters' },
    { left: 'Genetically identical', right: 'Genetically different' },
    { left: 'No crossing over', right: 'Crossing over in Prophase I' },
    { left: 'No synapsis/bivalent', right: 'Synapsis forms bivalents' },
    { left: 'Sister chromatids separate', right: 'Homologues separate in Meiosis I' },
    { left: 'Somatic cells (growth/repair)', right: 'Germ cells (gamete formation)' },
  ],
  steps: [
    {
      stepNumber: 1,
      highlightNodes: ['m-interphase', 'me-interphase'],
      explanation:
        'Both start the same way \u2014 DNA replicates once during S phase of interphase. Each chromosome now has 2 sister chromatids joined at the centromere.',
    },
    {
      stepNumber: 2,
      highlightNodes: ['m-prophase', 'me-prophase1'],
      explanation:
        'KEY DIFFERENCE in Prophase: In meiosis, homologous chromosomes pair up (synapsis) and crossing over occurs. In mitosis, chromosomes condense but do NOT pair up.',
    },
    {
      stepNumber: 3,
      highlightNodes: ['m-anaphase', 'me-ana1'],
      explanation:
        'KEY DIFFERENCE in Anaphase: In mitosis, sister chromatids separate. In Meiosis I, homologous chromosomes separate (reduction division) \u2014 this is when the chromosome number is halved.',
    },
    {
      stepNumber: 4,
      highlightNodes: ['m-result', 'me-result'],
      explanation:
        'Final result: Mitosis \u2192 2 diploid identical cells (for growth). Meiosis \u2192 4 haploid different cells (for reproduction). Meiosis creates genetic variation through crossing over + independent assortment.',
    },
  ],
}

export const animalCellDiagram: InteractiveDiagramData = {
  type: 'labeled-diagram',
  title: 'Animal Cell Structure',
  subtitle: 'Class 11 - Cell: The Unit of Life',
  nodes: [
    {
      id: 'cell-membrane',
      label: 'Cell Membrane',
      description:
        'Selectively permeable phospholipid bilayer with embedded proteins (Fluid Mosaic Model by Singer & Nicolson, 1972). Controls entry/exit of substances. Contains cholesterol for stability.',
      position: { x: 0.5, y: 0.05 },
      color: '#DEB887',
      size: 20,
    },
    {
      id: 'nucleus',
      label: 'Nucleus',
      description:
        'Control center of the cell. Contains chromatin (DNA + histone proteins). Bounded by double membrane (nuclear envelope) with nuclear pores. Contains nucleolus (site of rRNA synthesis).',
      position: { x: 0.45, y: 0.4 },
      style: 'primary',
      color: '#4169E1',
      size: 22,
    },
    {
      id: 'nucleolus',
      label: 'Nucleolus',
      description:
        'Dense, non-membrane bound structure inside the nucleus. Site of ribosomal RNA (rRNA) synthesis and ribosome subunit assembly. Disappears during cell division.',
      position: { x: 0.42, y: 0.35 },
      color: '#1A237E',
      size: 10,
    },
    {
      id: 'rough-er',
      label: 'Rough ER',
      description:
        'Endoplasmic reticulum studded with ribosomes. Synthesizes proteins destined for secretion, membranes, or lysosomes. Continuous with the nuclear envelope.',
      position: { x: 0.7, y: 0.3 },
      style: 'secondary',
      color: '#5D4037',
      size: 16,
    },
    {
      id: 'smooth-er',
      label: 'Smooth ER',
      description:
        'ER without ribosomes. Synthesizes lipids, steroids, and phospholipids. Detoxifies drugs and poisons (abundant in liver cells). Also stores calcium in muscle cells (sarcoplasmic reticulum).',
      position: { x: 0.72, y: 0.5 },
      style: 'secondary',
      color: '#795548',
      size: 16,
    },
    {
      id: 'mitochondria',
      label: 'Mitochondria',
      description:
        'Powerhouse of the cell. Double membrane organelle. Inner membrane has cristae (increase surface area for oxidative phosphorylation). Has its own circular DNA (70S ribosomes). Site of Krebs cycle and ETC. Produces 34-36 ATP per glucose.',
      position: { x: 0.25, y: 0.55 },
      style: 'highlight',
      color: '#FF6347',
      size: 18,
    },
    {
      id: 'golgi',
      label: 'Golgi Apparatus',
      description:
        'Stack of flattened membrane cisternae (dictyosomes). Modifies, packages, and sorts proteins from rough ER. Has cis face (receiving) and trans face (shipping). Forms lysosomes and secretory vesicles.',
      position: { x: 0.65, y: 0.7 },
      color: '#FF8F00',
      size: 16,
    },
    {
      id: 'lysosome',
      label: 'Lysosomes',
      description:
        'Suicide bags of the cell (de Duve). Single membrane vesicles containing 40+ hydrolytic enzymes (acid hydrolases, pH 5). Digest worn-out organelles (autophagy), food particles, and pathogens.',
      position: { x: 0.3, y: 0.75 },
      style: 'danger',
      color: '#DC2626',
      size: 12,
    },
    {
      id: 'centrosome',
      label: 'Centrosome',
      description:
        'Contains 2 centrioles arranged perpendicular to each other. Organizes spindle fibers during cell division. Made of 9 triplets of microtubules (9+0 pattern). Absent in most plant cells.',
      position: { x: 0.35, y: 0.22 },
      color: '#6A1B9A',
      size: 12,
    },
    {
      id: 'ribosomes',
      label: 'Ribosomes (80S)',
      description:
        'Non-membrane bound organelles. Site of protein synthesis (translation). Eukaryotic ribosomes are 80S (60S + 40S subunits). Found free in cytoplasm or attached to rough ER.',
      position: { x: 0.78, y: 0.15 },
      color: '#00695C',
      size: 8,
    },
    {
      id: 'cytoplasm',
      label: 'Cytoplasm',
      description:
        'Gel-like substance (cytosol) filling the cell. Contains water, salts, organic molecules, and enzymes. Site of glycolysis. Cytoskeleton (microfilaments, microtubules, intermediate filaments) provides structural support.',
      position: { x: 0.2, y: 0.15 },
      color: '#FFF8DC',
      size: 20,
    },
  ],
  steps: [
    {
      stepNumber: 1,
      highlightNodes: ['cell-membrane', 'cytoplasm'],
      explanation:
        'The cell is bounded by the cell membrane (plasma membrane) \u2014 a selectively permeable phospholipid bilayer described by the Fluid Mosaic Model. The cytoplasm fills the interior.',
    },
    {
      stepNumber: 2,
      highlightNodes: ['nucleus', 'nucleolus'],
      explanation:
        'The nucleus is the control center, containing DNA organized as chromatin. The nucleolus inside it produces ribosomal RNA. The nuclear envelope has pores for RNA/protein transport.',
    },
    {
      stepNumber: 3,
      highlightNodes: ['rough-er', 'smooth-er', 'ribosomes'],
      explanation:
        'The endomembrane system: Rough ER (with 80S ribosomes) makes proteins; Smooth ER makes lipids and detoxifies drugs. Free ribosomes make cytoplasmic proteins.',
    },
    {
      stepNumber: 4,
      highlightNodes: ['golgi', 'lysosome'],
      explanation:
        'Golgi apparatus modifies and packages proteins from ER. It forms lysosomes (suicide bags) which contain digestive enzymes for intracellular digestion and autophagy.',
    },
    {
      stepNumber: 5,
      highlightNodes: ['mitochondria'],
      explanation:
        "Mitochondria (powerhouse) perform aerobic respiration: Krebs cycle in matrix, ETC on cristae. They have their own DNA and 70S ribosomes (endosymbiotic origin). Produce most of the cell's ATP.",
    },
    {
      stepNumber: 6,
      highlightNodes: ['centrosome'],
      explanation:
        'Centrosome with 2 centrioles organizes spindle fibers during mitosis/meiosis. Centrioles have 9+0 arrangement of microtubule triplets. Also forms basal bodies of cilia and flagella.',
    },
  ],
}
