import { NextRequest, NextResponse } from 'next/server'
import crypto from 'crypto'
import { prisma } from '@/lib/prisma'
import {
  loadPaperQuestions,
  scoreAnswers,
  parseBands,
  computeWaiver,
} from '@/lib/scholarship/scholarshipTest'

export const dynamic = 'force-dynamic'

/**
 * POST /api/scholarship/session/[token]/submit — server-side scoring (+4/−1)
 * against the frozen paper, waiver-band assignment, and the counselor hook:
 * an activity + a HIGH-priority follow-up task on the registrant's lead so
 * the result call happens while the scorecard is still exciting.
 */
export async function POST(request: NextRequest, context: { params: Promise<{ token: string }> }) {
  try {
    const { token } = await context.params
    const body = await request.json().catch(() => ({}))
    const answers: Record<string, string> =
      body && typeof body.answers === 'object' && body.answers ? body.answers : {}

    const registration = await prisma.scholarship_registrations.findUnique({
      where: { token },
      include: { test: true },
    })
    if (!registration) {
      return NextResponse.json({ success: false, error: 'Invalid exam link.' }, { status: 404 })
    }
    if (registration.status === 'COMPLETED') {
      return NextResponse.json({ success: true, data: { alreadySubmitted: true } })
    }
    const paperIds = (registration.paper as string[] | null) || []
    if (paperIds.length === 0) {
      return NextResponse.json(
        { success: false, error: 'Exam was never started.' },
        { status: 400 }
      )
    }

    const questions = await loadPaperQuestions(paperIds)
    const result = scoreAnswers(questions, answers)
    const bands = parseBands(registration.test.waiverBands)
    const waiverPercent = computeWaiver(result.percent, bands)

    const suspicious = Array.isArray(body.suspiciousActivity)
      ? body.suspiciousActivity.slice(0, 200)
      : undefined

    await prisma.scholarship_registrations.update({
      where: { id: registration.id },
      data: {
        status: 'COMPLETED',
        completedAt: new Date(),
        score: result.score,
        maxScore: result.maxScore,
        correctCount: result.correct,
        incorrectCount: result.incorrect,
        percent: result.percent,
        waiverPercent,
        answerState: { answers },
        ...(suspicious ? { suspicious } : {}),
      },
    })

    // Counselor hook — best-effort, never fails the submit.
    if (registration.leadId) {
      const summary = `${registration.studentName} scored ${result.score}/${result.maxScore} (${result.percent}%) in ${registration.test.name} — earned a ${waiverPercent}% fee waiver`
      try {
        const lead = await prisma.leads.findUnique({
          where: { id: registration.leadId },
          select: { id: true, assignedToId: true },
        })
        if (lead) {
          await prisma.activities.create({
            data: {
              id: crypto.randomUUID(),
              userId: lead.assignedToId,
              leadId: lead.id,
              action: 'NOTE_ADDED',
              description: `Scholarship test completed: ${summary}`,
              metadata: {
                registrationId: registration.id,
                score: result.score,
                percent: result.percent,
                waiverPercent,
              },
            },
          })
          await prisma.tasks.create({
            data: {
              id: crypto.randomUUID(),
              leadId: lead.id,
              title: `Scholarship result call — ${registration.studentName} (${waiverPercent}% waiver)`,
              description: `${summary}.\n\nCall while the result is fresh: congratulate, explain the waiver on their course fee, and book the admission counseling session.`,
              type: 'FOLLOW_UP_CALL',
              priority: 'HIGH',
              status: 'PENDING',
              dueDate: new Date(),
              assignedToId: lead.assignedToId,
              isAutoGenerated: true,
              triggerEvent: 'scholarship_test_completed',
              updatedAt: new Date(),
            },
          })
        }
      } catch (hookError) {
        console.error('[scholarship/submit] counselor hook failed:', hookError)
      }
    }

    return NextResponse.json({
      success: true,
      data: {
        correct: result.correct,
        incorrect: result.incorrect,
        unattempted: result.unattempted,
        score: result.score,
        maxScore: result.maxScore,
        percent: result.percent,
        waiverPercent,
      },
    })
  } catch (error) {
    console.error('[scholarship/submit] failed:', error)
    return NextResponse.json({ success: false, error: 'Submit failed.' }, { status: 500 })
  }
}
