/**
 * ARIA Lead Capture API
 * Saves leads from Aria chatbot and sends WhatsApp notifications
 */

import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { processContentLead } from '@/lib/whatsapp/contentLeadFollowup'
import { sendWhatsAppMessage } from '@/lib/interakt'
import { logger } from '@/lib/utils/logger'

const ADMIN_PHONE = process.env.ADMIN_WHATSAPP_NUMBER || '+918826444334'

interface AriaLeadRequest {
  name: string
  phone: string
  studentClass?: string
  sessionId?: string
  conversationSummary?: string
  source?: string
  currentPage?: string
}

export async function POST(request: NextRequest) {
  try {
    const body: AriaLeadRequest = await request.json()
    const { name, phone, studentClass, sessionId, conversationSummary, source, currentPage } = body

    // Validate required fields
    if (!phone) {
      return NextResponse.json({ error: 'Phone is required' }, { status: 400 })
    }

    // Normalize phone
    const normalizedPhone = phone.replace(/\D/g, '').slice(-10)
    if (normalizedPhone.length !== 10) {
      return NextResponse.json({ error: 'Invalid phone number' }, { status: 400 })
    }

    const leadId = `aria_${Date.now()}_${Math.random().toString(36).substring(7)}`

    // Check for existing lead
    const existingLead = await prisma.leads.findFirst({
      where: { phone: normalizedPhone },
    })

    if (existingLead) {
      // Update existing lead with new info
      await prisma.leads.update({
        where: { id: existingLead.id },
        data: {
          studentName: name || existingLead.studentName,
          updatedAt: new Date(),
        },
      })

      logger.info('Aria lead updated (existing)', {
        service: 'aria-lead',
        existingLeadId: existingLead.id,
        phone: normalizedPhone,
      })

      // Still notify admin about re-engagement
      await notifyAdminAriaLead({
        name,
        phone: normalizedPhone,
        studentClass,
        conversationSummary,
        currentPage,
        isReturning: true,
      })

      return NextResponse.json({
        success: true,
        message: 'Lead updated',
        leadId: existingLead.id,
        isExisting: true,
      })
    }

    // Find counselor for assignment
    const counselor = await prisma.users.findFirst({
      where: {
        role: { in: ['COUNSELOR', 'ADMIN'] },
        isActive: true,
      },
      orderBy: { leads: { _count: 'asc' } },
      select: { id: true, name: true },
    })

    // Create new lead in CRM
    const newLead = await prisma.leads.create({
      data: {
        id: leadId,
        studentName: name || 'Aria Chat User',
        phone: normalizedPhone,
        courseInterest: studentClass
          ? `NEET Biology - ${studentClass}`
          : 'NEET Biology (from Aria chat)',
        stage: 'NEW_LEAD',
        priority: 'HOT', // Chat leads are hot!
        source: 'CHATBOT',
        sourceDetail: `Aria AI Chat - ${currentPage || 'Homepage'}`,
        assignedToId: counselor?.id,
        nextFollowUpAt: new Date(Date.now() + 30 * 60 * 1000), // 30 mins - urgent!
        updatedAt: new Date(),
      },
    })

    logger.info('Aria lead created', {
      service: 'aria-lead',
      leadId: newLead.id,
      phone: normalizedPhone,
      name,
    })

    // Create task for counselor
    if (counselor) {
      await prisma.tasks.create({
        data: {
          title: `🔥 HOT LEAD from AI Chat - ${name || 'Unknown'}`,
          description: `Lead from Aria AI chatbot. They engaged in conversation and shared contact details.

Phone: ${normalizedPhone}
Class: ${studentClass || 'Not specified'}
Page: ${currentPage || 'Unknown'}
${conversationSummary ? `\nConversation Summary:\n${conversationSummary}` : ''}

⚡ CALL WITHIN 30 MINUTES for best conversion!`,
          type: 'FOLLOW_UP_CALL',
          priority: 'URGENT',
          dueDate: new Date(Date.now() + 30 * 60 * 1000),
          status: 'PENDING',
          leadId: newLead.id,
          assignedToId: counselor.id,
          createdById: counselor.id,
          isAutoGenerated: true,
          triggerEvent: 'aria_lead_captured',
        },
      })
    }

    // Log activity
    await prisma.activities.create({
      data: {
        leadId: newLead.id,
        userId: counselor?.id || 'system',
        action: 'LEAD_CREATED',
        description: `Lead captured from Aria AI chatbot on ${currentPage || 'website'}`,
        metadata: {
          source: 'aria_chatbot',
          sessionId,
          studentClass,
          currentPage,
        },
      },
    })

    // Send WhatsApp notification to admin (high priority!)
    await notifyAdminAriaLead({
      name,
      phone: normalizedPhone,
      studentClass,
      conversationSummary,
      currentPage,
      isReturning: false,
    })

    // Send welcome message to the lead
    await processContentLead({
      phone: normalizedPhone,
      name,
      source: 'aria_chatbot',
      leadId: newLead.id,
    })

    return NextResponse.json({
      success: true,
      message: 'Lead captured successfully',
      leadId: newLead.id,
      assignedTo: counselor?.name,
    })
  } catch (error) {
    logger.error('Aria lead capture error', {
      service: 'aria-lead',
      error: error instanceof Error ? error.message : 'Unknown error',
    })

    return NextResponse.json({ error: 'Failed to capture lead' }, { status: 500 })
  }
}

async function notifyAdminAriaLead(params: {
  name?: string
  phone: string
  studentClass?: string
  conversationSummary?: string
  currentPage?: string
  isReturning: boolean
}) {
  const { name, phone, studentClass, conversationSummary, currentPage, isReturning } = params
  const timestamp = new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })

  const message = `🤖 *${isReturning ? 'RETURNING' : 'NEW'} ARIA CHATBOT LEAD*

📱 Phone: ${phone}
👤 Name: ${name || 'Not provided'}
📚 Class: ${studentClass || 'Not specified'}
📍 Page: ${currentPage || 'Unknown'}
⏰ Time: ${timestamp}

${conversationSummary ? `💬 *Conversation:*\n${conversationSummary.slice(0, 200)}...` : ''}

🔥 *THIS IS A HOT LEAD!*
They actively chatted and shared their number.

⚡ *CALL WITHIN 30 MINUTES!*`

  try {
    await sendWhatsAppMessage({
      phone: ADMIN_PHONE,
      message,
    })
    return { success: true }
  } catch (error) {
    logger.error('Failed to notify admin of Aria lead', { error })
    return { success: false }
  }
}
