/**
 * ARIA Lead Capture API
 * Saves leads from Aria chatbot and sends WhatsApp notifications
 */

import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { processContentLead } from '@/lib/whatsapp/contentLeadFollowup'
import { sendTemplateMessage } from '@/lib/interakt'
import { UTILITY_TEMPLATES } from '@/lib/interakt-templates'
import { logger } from '@/lib/utils/logger'
import { upsertLeadCore } from '@/lib/leads/upsertLead'
import { updateLeadScore } from '@/lib/leadScoring'

const ADMIN_PHONE = process.env.ADMIN_WHATSAPP_NUMBER || '+918826444334'

interface AriaLeadRequest {
  name: string
  phone: string
  studentClass?: string
  sessionId?: string
  conversationSummary?: string
  source?: string
  currentPage?: string
}

export async function POST(request: NextRequest) {
  try {
    const body: AriaLeadRequest = await request.json()
    const { name, phone, studentClass, sessionId, conversationSummary, source, currentPage } = body

    // Validate required fields
    if (!phone) {
      return NextResponse.json({ error: 'Phone is required' }, { status: 400 })
    }

    // Normalize phone — accept international (8-15 digits); keep last 10 for dedup.
    const phoneDigits = phone.replace(/\D/g, '')
    if (phoneDigits.length < 8 || phoneDigits.length > 15) {
      return NextResponse.json({ error: 'Invalid phone number' }, { status: 400 })
    }
    const normalizedPhone = phoneDigits.slice(-10)

    // Canonical CRM write: dedup by phone, create-or-touch with
    // phoneNormalized stamped. ARIA keeps its own task/notification/welcome
    // side effects, so skipTask + core (not the generic wrapper).
    const result = await upsertLeadCore(prisma, {
      name: name || 'Aria Chat User',
      phone: normalizedPhone,
      courseInterest: studentClass
        ? `NEET Biology - ${studentClass} (Aria Chat)`
        : 'NEET Biology (from Aria chat)',
      source: `aria_chatbot${currentPage ? `:${currentPage}` : ''}`,
      message: conversationSummary?.slice(0, 300) || null,
      priority: 'HOT', // Chat leads are hot!
      skipTask: true,
    })

    if (!result.created) {
      logger.info('Aria lead updated (existing)', {
        service: 'aria-lead',
        existingLeadId: result.leadId,
        phone: normalizedPhone,
      })

      // Still notify admin about re-engagement
      await notifyAdminAriaLead({
        name,
        phone: normalizedPhone,
        studentClass,
        conversationSummary,
        currentPage,
        isReturning: true,
      })

      void updateLeadScore(result.leadId).catch(() => {})

      return NextResponse.json({
        success: true,
        message: 'Lead updated',
        leadId: result.leadId,
        isExisting: true,
      })
    }

    logger.info('Aria lead created', {
      service: 'aria-lead',
      leadId: result.leadId,
      phone: normalizedPhone,
      name,
    })

    // Create ARIA-specific task for the assigned counselor
    const taskId = `task_${Date.now()}_${Math.random().toString(36).substring(7)}`
    await prisma.tasks.create({
      data: {
        id: taskId,
        title: `🔥 HOT LEAD from AI Chat - ${name || 'Unknown'}`,
        description: `Lead from Aria AI chatbot. They engaged in conversation and shared contact details.

Phone: ${normalizedPhone}
Class: ${studentClass || 'Not specified'}
Page: ${currentPage || 'Unknown'}
${conversationSummary ? `\nConversation Summary:\n${conversationSummary}` : ''}

⚡ CALL WITHIN 30 MINUTES for best conversion!`,
        type: 'FOLLOW_UP_CALL',
        priority: 'HIGH',
        dueDate: new Date(Date.now() + 30 * 60 * 1000),
        status: 'PENDING',
        leadId: result.leadId,
        assignedToId: result.assignedToId,
        createdById: result.assignedToId,
        isAutoGenerated: true,
        triggerEvent: 'aria_lead_captured',
        updatedAt: new Date(),
      },
    })

    // Send WhatsApp notification to admin (high priority!)
    await notifyAdminAriaLead({
      name,
      phone: normalizedPhone,
      studentClass,
      conversationSummary,
      currentPage,
      isReturning: false,
    })

    // Send welcome message to the lead
    await processContentLead({
      phone: normalizedPhone,
      name,
      source: 'aria_chatbot',
      leadId: result.leadId,
    })

    void updateLeadScore(result.leadId).catch(() => {})

    return NextResponse.json({
      success: true,
      message: 'Lead captured successfully',
      leadId: result.leadId,
    })
  } catch (error) {
    logger.error('Aria lead capture error', {
      service: 'aria-lead',
      error: error instanceof Error ? error.message : 'Unknown error',
    })

    return NextResponse.json({ error: 'Failed to capture lead' }, { status: 500 })
  }
}

async function notifyAdminAriaLead(params: {
  name?: string
  phone: string
  studentClass?: string
  conversationSummary?: string
  currentPage?: string
  isReturning: boolean
}) {
  const { name, phone, studentClass, conversationSummary, currentPage, isReturning } = params
  const timestamp = new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })

  // Use 'class_reminder' template (APPROVED) - repurposed for lead alerts
  // Template: Hi {{1}}, Your class starts in {{2}}: Subject: {{3}}, Topic: {{4}}, Faculty: {{5}}, Join: {{6}}
  try {
    await sendTemplateMessage({
      phone: ADMIN_PHONE,
      templateName: UTILITY_TEMPLATES.CLASS_REMINDER.name, // 'class_reminder'
      bodyValues: [
        `🔥 ${isReturning ? 'RETURNING' : 'NEW'} LEAD`,
        `${name || 'Unknown'} - ${phone}`,
        studentClass ? `NEET Biology - ${studentClass}` : 'NEET Biology',
        conversationSummary?.slice(0, 100) || 'Chatbot inquiry',
        `Aria Chat - ${currentPage || 'Homepage'}`,
        `Call NOW! ${timestamp}`,
      ],
    })
    logger.info('Admin notified via template', { service: 'aria-lead', phone })
    return { success: true }
  } catch (error) {
    logger.error('Failed to notify admin of Aria lead', { error })
    return { success: false }
  }
}
