import { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://www.cerebrumbiologyacademy.com'
  // Use a static date representing when site content was last updated
  // This is better for SEO than dynamic dates that change on every build
  const lastUpdated = new Date('2025-12-01T00:00:00.000Z')

  const routes = [
    {
      url: baseUrl,
      lastModified: lastUpdated,
      changeFrequency: 'daily' as const,
      priority: 1.0,
    },
    {
      url: `${baseUrl}/ai-education-demo`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/courses`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/enrollment`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/pricing`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/mock-tests`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/about`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    {
      url: `${baseUrl}/contact`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    {
      url: `${baseUrl}/resources`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.7,
    },
    {
      url: `${baseUrl}/free-resources`,
      lastModified: lastUpdated,
      changeFrequency: 'daily' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/testimonials`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.7,
    },
    {
      url: `${baseUrl}/faculty`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    {
      url: `${baseUrl}/blog`,
      lastModified: lastUpdated,
      changeFrequency: 'daily' as const,
      priority: 0.6,
    },
    // Blog Posts - 17 total MDX files
    {
      url: `${baseUrl}/blog/kota-vs-online-neet-coaching-2025`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    {
      url: `${baseUrl}/blog/when-to-start-neet-preparation-class-9-vs-10`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    {
      url: `${baseUrl}/blog/dps-students-neet-preparation-guide`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    {
      url: `${baseUrl}/blog/top-10-neet-biology-coaching-delhi-ncr-2025`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    {
      url: `${baseUrl}/blog/best-books-for-neet-2026-biology-physics-chemistry`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    {
      url: `${baseUrl}/blog/common-mistakes-neet-aspirants-avoid-2026`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    {
      url: `${baseUrl}/blog/last-6-months-neet-2026-preparation-strategy`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    {
      url: `${baseUrl}/blog/mock-test-strategy-neet-2026-complete-guide`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    {
      url: `${baseUrl}/blog/ncert-reading-strategy-neet-biology-2026`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    {
      url: `${baseUrl}/blog/neet-2026-complete-guide-exam-pattern-syllabus-dates`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    {
      url: `${baseUrl}/blog/neet-biology-chapter-wise-weightage-2026`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    {
      url: `${baseUrl}/blog/neet-biology-coaching-delhi-ncr-guide`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    {
      url: `${baseUrl}/blog/neet-biology-preparation-strategy-score-180-plus`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    {
      url: `${baseUrl}/blog/neet-biology-syllabus-2025-complete-guide`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    {
      url: `${baseUrl}/blog/photosynthesis-vs-respiration-neet-comparison`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    {
      url: `${baseUrl}/blog/ultimate-neet-2025-guide-specialized-vs-mass-coaching`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    {
      url: `${baseUrl}/blog/what-neet-toppers-do-differently-secrets-revealed`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    {
      url: `${baseUrl}/gallery`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.6,
    },
    {
      url: `${baseUrl}/results`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.6,
    },
    {
      url: `${baseUrl}/success-stories`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.6,
    },
    {
      url: `${baseUrl}/locations`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.5,
    },
    {
      url: `${baseUrl}/locations/mumbai`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/locations/bangalore`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/demo-booking`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.5,
    },
    {
      url: `${baseUrl}/class-11`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/class-12`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/class-9-foundation`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/class-10-foundation`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/early-neet-preparation`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/neet-foundation-course`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/dropper`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/neet-repeaters`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    {
      url: `${baseUrl}/study-materials`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.7,
    },
    {
      url: `${baseUrl}/video-lectures`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.7,
    },
    {
      url: `${baseUrl}/services`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.6,
    },
    {
      url: `${baseUrl}/admissions`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/compare`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.5,
    },
    {
      url: `${baseUrl}/compare/kota-vs-online`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/compare/class-9-vs-class-10-foundation`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.8,
    },
    // NEET Year-specific Landing Pages - HIGH PRIORITY
    {
      url: `${baseUrl}/neet-2026-preparation`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.98,
    },
    // NEET 2026 SEO Pages - HIGH TRAFFIC KEYWORDS
    {
      url: `${baseUrl}/neet-2026-exam-date`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.98,
    },
    {
      url: `${baseUrl}/neet-2026-cutoff`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.97,
    },
    {
      url: `${baseUrl}/neet-biology-syllabus-2026`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.96,
    },
    // NEET Free Tools - HIGH ENGAGEMENT
    {
      url: `${baseUrl}/neet-rank-predictor`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.97,
    },
    {
      url: `${baseUrl}/neet-college-predictor`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.97,
    },
    {
      url: `${baseUrl}/neet-biology-mcq`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.96,
    },
    // Regional Online Service Pages - HIGH PRIORITY
    {
      url: `${baseUrl}/neet-coaching-north-india`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    {
      url: `${baseUrl}/neet-coaching-south-india`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    {
      url: `${baseUrl}/neet-coaching-east-india`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    {
      url: `${baseUrl}/neet-coaching-west-india`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    {
      url: `${baseUrl}/neet-coaching-overseas`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    // NEET Coaching SEO Pages - High Traffic Keywords
    {
      url: `${baseUrl}/best-neet-coaching`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    {
      url: `${baseUrl}/neet-coaching-centre`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    {
      url: `${baseUrl}/neet-coaching-institute`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    {
      url: `${baseUrl}/neet-classes`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    {
      url: `${baseUrl}/neet-preparation`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    {
      url: `${baseUrl}/neet-biology-classes`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    // Pan-India SEO Landing Pages - High Priority
    {
      url: `${baseUrl}/online-neet-coaching-india`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    {
      url: `${baseUrl}/best-neet-coaching-india`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    {
      url: `${baseUrl}/neet-biology-coaching-india`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    {
      url: `${baseUrl}/online-medical-coaching-india`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    // Delhi NCR Key Localities - High Priority
    {
      url: `${baseUrl}/laxmi-nagar`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/locations/delhi/dwarka`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/locations/delhi/rohini`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/locations/delhi/south-delhi`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/locations/noida/sector-18`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/locations/noida/sector-62`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    // Gurugram/Gurgaon Key Localities - HIGH PRIORITY for Gurugram Domination
    {
      url: `${baseUrl}/neet-coaching-gurugram`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    {
      url: `${baseUrl}/locations/gurugram/dlf-phase-1`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/locations/gurugram/golf-course-road`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/locations/gurugram/sushant-lok`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/locations/gurugram/sector-56`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/locations/gurugram/sector-14`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/locations/gurugram/sector-43`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/locations/gurugram/sector-51`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/locations/gurugram/sector-57`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/locations/gurugram/south-city-1`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/locations/gurugram/new-gurugram`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/locations/gurugram/dlf-phase-4`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    // NEW Premium Gurugram Localities (Based on Market Research)
    {
      url: `${baseUrl}/locations/gurugram/nirvana-country`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/locations/gurugram/sector-49`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/locations/gurugram/sohna-road`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/locations/gurugram/sector-84`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/locations/gurugram/dlf-phase-2`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/locations/gurugram/dlf-phase-3`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/locations/gurugram/dlf-phase-5`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    // Phase 3 Gurugram Localities - Ultra Premium & Dwarka Expressway
    {
      url: `${baseUrl}/locations/gurugram/mg-road`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/locations/gurugram/sector-54`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/locations/gurugram/sector-58`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/locations/gurugram/sector-53`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/locations/gurugram/ambience-island`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/locations/gurugram/sector-45`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/locations/gurugram/sector-48`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/locations/gurugram/sector-62`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/locations/gurugram/sector-63`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/locations/gurugram/sector-41`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/locations/gurugram/sector-102`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/locations/gurugram/sector-106`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/locations/gurugram/sector-109`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/locations/gurugram/sector-111`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/locations/gurugram/sector-113`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/course-finder`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.6,
    },
    // Noida SEO Landing Pages - HIGH PRIORITY
    {
      url: `${baseUrl}/neet-coaching-noida`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    {
      url: `${baseUrl}/neet-coaching-noida/sector-18`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/neet-coaching-noida/sector-62`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/neet-coaching-noida/sector-137`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/neet-coaching-noida/sector-150`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/neet-coaching-noida/sector-44`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/neet-coaching-noida/sector-50`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/neet-coaching-noida/sector-37`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/neet-coaching-noida/sector-93`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/neet-coaching-noida/sector-104`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/neet-coaching-noida/sector-128`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/neet-coaching-noida/sector-15a`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/neet-coaching-noida/sector-168`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/neet-coaching-noida/greater-noida-west`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/neet-coaching-greater-noida-west`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    {
      url: `${baseUrl}/privacy-policy`,
      lastModified: lastUpdated,
      changeFrequency: 'yearly' as const,
      priority: 0.3,
    },
    {
      url: `${baseUrl}/terms-of-service`,
      lastModified: lastUpdated,
      changeFrequency: 'yearly' as const,
      priority: 0.3,
    },
    {
      url: `${baseUrl}/refund-policy`,
      lastModified: lastUpdated,
      changeFrequency: 'yearly' as const,
      priority: 0.3,
    },
    {
      url: `${baseUrl}/disclaimer`,
      lastModified: lastUpdated,
      changeFrequency: 'yearly' as const,
      priority: 0.3,
    },
    // Biology Topics Pages - High SEO value
    {
      url: `${baseUrl}/biology-topics`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/biology-topics/cell-biology`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/biology-topics/genetics-evolution`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/biology-topics/human-physiology`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/biology-topics/plant-physiology`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/biology-topics/ecology-environment`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/biology-topics/biotechnology`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    // Ghaziabad SEO Landing Pages - HIGH PRIORITY
    {
      url: `${baseUrl}/neet-coaching-ghaziabad`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    {
      url: `${baseUrl}/neet-coaching-ghaziabad/indirapuram`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/neet-coaching-ghaziabad/vaishali`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/neet-coaching-ghaziabad/vasundhara`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/neet-coaching-ghaziabad/crossing-republik`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/neet-coaching-ghaziabad/raj-nagar-extension`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/neet-coaching-ghaziabad/kaushambi`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/neet-coaching-ghaziabad/mohan-nagar`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/neet-coaching-ghaziabad/sahibabad`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    // Faridabad SEO Landing Pages - HIGH PRIORITY
    {
      url: `${baseUrl}/neet-coaching-faridabad`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    {
      url: `${baseUrl}/neet-coaching-faridabad/greater-faridabad`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/neet-coaching-faridabad/sector-21`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/neet-coaching-faridabad/nit-faridabad`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/neet-coaching-faridabad/ballabgarh`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/neet-coaching-faridabad/sector-15`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/neet-coaching-faridabad/neharpar`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/neet-coaching-faridabad/sector-86`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/neet-coaching-faridabad/old-faridabad`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    // Biology Tuition & Coaching Pages - HIGH PRIORITY
    {
      url: `${baseUrl}/biology-tuition-ghaziabad`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    {
      url: `${baseUrl}/biology-tuition-faridabad`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    {
      url: `${baseUrl}/biology-coaching-class-11`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/biology-coaching-class-12`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/biology-coaching-droppers`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/biology-tuition-class-9-10`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    // South Delhi SEO Landing Pages - HIGH PRIORITY
    {
      url: `${baseUrl}/neet-coaching-south-delhi`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    {
      url: `${baseUrl}/neet-coaching-south-delhi/hauz-khas`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/neet-coaching-south-delhi/kalu-sarai`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/neet-coaching-south-delhi/greater-kailash`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/neet-coaching-south-delhi/defence-colony`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/neet-coaching-south-delhi/vasant-vihar`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/neet-coaching-south-delhi/saket`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/neet-coaching-south-delhi/malviya-nagar`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/neet-coaching-south-delhi/green-park`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/neet-coaching-south-delhi/panchsheel-park`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/neet-coaching-south-delhi/new-friends-colony`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/neet-coaching-south-delhi/cr-park`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/neet-coaching-south-delhi/vasant-kunj`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    // Government Officer Colonies - South Delhi
    {
      url: `${baseUrl}/neet-coaching-south-delhi/rk-puram`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/neet-coaching-south-delhi/sarojini-nagar`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/neet-coaching-south-delhi/lodhi-colony`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/neet-coaching-south-delhi/andrews-ganj`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/neet-coaching-south-delhi/kidwai-nagar`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/neet-coaching-south-delhi/netaji-nagar`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/neet-coaching-south-delhi/moti-bagh`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    // Ultra-Premium Lutyens Delhi
    {
      url: `${baseUrl}/neet-coaching-south-delhi/golf-links`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/neet-coaching-south-delhi/jor-bagh`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/neet-coaching-south-delhi/sunder-nagar`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    // Student Hub Areas
    {
      url: `${baseUrl}/neet-coaching-south-delhi/munirka`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/neet-coaching-south-delhi/ber-sarai`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/neet-coaching-south-delhi/katwaria-sarai`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/neet-coaching-south-delhi/lajpat-nagar`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/neet-coaching-south-delhi/kalkaji`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    // Premium Residential Areas
    {
      url: `${baseUrl}/neet-coaching-south-delhi/safdarjung-enclave`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/neet-coaching-south-delhi/gulmohar-park`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/neet-coaching-south-delhi/east-of-kailash`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/neet-coaching-south-delhi/alaknanda`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/neet-coaching-south-delhi/sukhdev-vihar`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/neet-coaching-south-delhi/okhla`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    // Central Delhi Coaching Hubs
    {
      url: `${baseUrl}/neet-coaching-south-delhi/rajendra-nagar`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/neet-coaching-south-delhi/karol-bagh`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/neet-coaching-south-delhi/civil-lines`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    // Near School SEO Pages - HIGH INTENT
    {
      url: `${baseUrl}/neet-coaching-near`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/neet-coaching-near/dps-rk-puram`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/neet-coaching-near/dps-vasant-vihar`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/neet-coaching-near/vasant-valley-school`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/neet-coaching-near/modern-school-vasant-vihar`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/neet-coaching-near/sanskriti-school`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/neet-coaching-near/shri-ram-school`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/neet-coaching-near/springdales-pusa-road`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/neet-coaching-near/dps-east-of-kailash`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    // Biology Tuition South Delhi - Hub Page
    {
      url: `${baseUrl}/biology-tuition-south-delhi`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    // Biology Tuition Area Pages
    {
      url: `${baseUrl}/biology-tuition-south-delhi/hauz-khas`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/biology-tuition-south-delhi/kalu-sarai`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/biology-tuition-south-delhi/greater-kailash`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/biology-tuition-south-delhi/defence-colony`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/biology-tuition-south-delhi/vasant-vihar`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/biology-tuition-south-delhi/rk-puram`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/biology-tuition-south-delhi/sarojini-nagar`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/biology-tuition-south-delhi/lodhi-colony`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/biology-tuition-south-delhi/saket`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/biology-tuition-south-delhi/malviya-nagar`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/biology-tuition-south-delhi/green-park`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/biology-tuition-south-delhi/cr-park`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/biology-tuition-south-delhi/munirka`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/biology-tuition-south-delhi/lajpat-nagar`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/biology-tuition-south-delhi/kalkaji`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/biology-tuition-south-delhi/east-of-kailash`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    // Biology Tutor SEO Pages - High Traffic Keywords
    {
      url: `${baseUrl}/biology-tutor`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.94,
    },
    {
      url: `${baseUrl}/biology-tutors-near-me`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.94,
    },
    {
      url: `${baseUrl}/biology-home-tutor`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.94,
    },
    {
      url: `${baseUrl}/biology-tutor-class-11-cbse`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.94,
    },
    {
      url: `${baseUrl}/biology-tutor-class-12-cbse`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.94,
    },
    {
      url: `${baseUrl}/biology-tutor-class-11-icse`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.94,
    },
    {
      url: `${baseUrl}/biology-tutor-class-12-icse`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.94,
    },
    {
      url: `${baseUrl}/biology-tutor-state-boards`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.94,
    },
    // Biology Teacher SEO Pages - High Traffic Keywords
    {
      url: `${baseUrl}/biology-teacher`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.94,
    },
    {
      url: `${baseUrl}/biology-teacher-near-me`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.94,
    },
    {
      url: `${baseUrl}/best-biology-teacher-for-neet`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.94,
    },
    {
      url: `${baseUrl}/best-biology-teacher-class-11-cbse`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.94,
    },
    {
      url: `${baseUrl}/best-biology-teacher-class-12-cbse`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.94,
    },
    {
      url: `${baseUrl}/best-biology-teacher-class-11-icse`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.94,
    },
    {
      url: `${baseUrl}/best-biology-teacher-class-12-icse`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.94,
    },
    // Biology Classes SEO Pages - High Traffic Keywords
    {
      url: `${baseUrl}/biology-classes`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.94,
    },
    {
      url: `${baseUrl}/biology-classes-near-me`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.94,
    },
    {
      url: `${baseUrl}/biology-coaching`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.94,
    },
    {
      url: `${baseUrl}/home-tuition-for-biology`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.94,
    },
    {
      url: `${baseUrl}/biology-tuition-class-11`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.94,
    },
    {
      url: `${baseUrl}/biology-tuition-class-12`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.94,
    },
    {
      url: `${baseUrl}/biology-neet-preparation`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.94,
    },
    {
      url: `${baseUrl}/pcb-tuition-near-me`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.94,
    },
    {
      url: `${baseUrl}/biology-tuition-near-me`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.94,
    },
    // Zoology Teacher SEO Pages
    {
      url: `${baseUrl}/zoology-teacher`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.94,
    },
    {
      url: `${baseUrl}/zoology-teacher-near-me`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.94,
    },
    {
      url: `${baseUrl}/best-zoology-teacher-for-neet`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.94,
    },
    {
      url: `${baseUrl}/zoology-classes`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.94,
    },
    // Botany Teacher SEO Pages
    {
      url: `${baseUrl}/botany-teacher`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.94,
    },
    {
      url: `${baseUrl}/botany-teacher-near-me`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.94,
    },
    {
      url: `${baseUrl}/best-botany-teacher-for-neet`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.94,
    },
    {
      url: `${baseUrl}/botany-classes`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.94,
    },
    // Online NEET Coaching SEO Pages
    {
      url: `${baseUrl}/online-neet-coaching`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    {
      url: `${baseUrl}/neet-online-classes`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    {
      url: `${baseUrl}/neet-online-course`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    {
      url: `${baseUrl}/neet-online`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    // Online Biology SEO Pages - High Traffic Keywords
    {
      url: `${baseUrl}/online-biology-classes`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    {
      url: `${baseUrl}/best-biology-teacher-online`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    {
      url: `${baseUrl}/best-online-biology-teacher-for-neet`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    {
      url: `${baseUrl}/biology-tutor-online`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    // Class 9 Biology SEO Pages
    {
      url: `${baseUrl}/biology-tutor-class-9-cbse`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.93,
    },
    {
      url: `${baseUrl}/biology-tutor-class-9-icse`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.93,
    },
    {
      url: `${baseUrl}/class-9-science-tuition`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.93,
    },
    // NEET Foundation SEO Pages
    {
      url: `${baseUrl}/neet-foundation-class-9`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.94,
    },
    {
      url: `${baseUrl}/neet-foundation-class-10`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.94,
    },
    {
      url: `${baseUrl}/pre-neet-coaching`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.94,
    },
    // NTSE Preparation SEO Pages
    {
      url: `${baseUrl}/ntse-biology-preparation`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.93,
    },
    {
      url: `${baseUrl}/ntse-online-classes`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.93,
    },
    // Olympiad Preparation SEO Pages
    {
      url: `${baseUrl}/biology-olympiad-coaching`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.93,
    },
    {
      url: `${baseUrl}/olympiad-preparation`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.93,
    },
    // NCERT Biology Books SEO Pages - High Traffic Keywords
    {
      url: `${baseUrl}/ncert-biology-class-11`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    {
      url: `${baseUrl}/ncert-biology-class-12`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    {
      url: `${baseUrl}/ncert-fingertips-biology`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.94,
    },
    {
      url: `${baseUrl}/trueman-biology-for-neet`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.94,
    },
    {
      url: `${baseUrl}/best-biology-books-for-neet`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    // International Curriculum Biology SEO Pages
    {
      url: `${baseUrl}/igcse-biology-tutor`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.94,
    },
    {
      url: `${baseUrl}/ap-biology-tutor`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.94,
    },
    {
      url: `${baseUrl}/a-level-biology-tutor`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.94,
    },
    {
      url: `${baseUrl}/ib-biology-tutor`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.94,
    },
    {
      url: `${baseUrl}/international-biology-tutor`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    {
      url: `${baseUrl}/biology-major-courses`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.94,
    },
    // Critical Conversion & Feature Pages
    {
      url: `${baseUrl}/demo`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    {
      url: `${baseUrl}/help`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.6,
    },
    {
      url: `${baseUrl}/ai-features`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/interactive-learning`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/mobile-app`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/scholarship`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/dr-shekhar-singh`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/referral`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    {
      url: `${baseUrl}/community`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.7,
    },
    {
      url: `${baseUrl}/adaptive-testing`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/learning-path`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/curriculum`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    {
      url: `${baseUrl}/offline`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/explore-courses`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    // About Sub-Pages
    {
      url: `${baseUrl}/about/careers`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.6,
    },
    {
      url: `${baseUrl}/about/faculty`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    {
      url: `${baseUrl}/about/media`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.6,
    },
    {
      url: `${baseUrl}/about/results`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    // Boards Hub and Pages
    {
      url: `${baseUrl}/boards`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/boards/cbse`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/boards/icse`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/boards/ib`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/boards/igcse`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/boards/state-boards`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    // Major City NEET Coaching Pages
    {
      url: `${baseUrl}/neet-coaching-bangalore`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    {
      url: `${baseUrl}/neet-coaching-chennai`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    {
      url: `${baseUrl}/neet-coaching-mumbai`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    {
      url: `${baseUrl}/neet-coaching-pune`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    {
      url: `${baseUrl}/neet-coaching-hyderabad`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    {
      url: `${baseUrl}/best-neet-coaching-delhi-ncr`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.96,
    },
    {
      url: `${baseUrl}/neet-coaching-gurgaon`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    // Delhi Area NEET Coaching Pages
    {
      url: `${baseUrl}/neet-coaching-north-delhi`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/neet-coaching-east-delhi`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/neet-coaching-west-delhi`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/neet-coaching-gtb-nagar`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/neet-coaching-kalu-sarai`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/neet-coaching-mukherjee-nagar`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/neet-coaching-rajinder-nagar`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/neet-coaching-janakpuri`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/neet-coaching-lajpat-nagar`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    // NEET Content Hub Pages
    {
      url: `${baseUrl}/neet-biology`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/neet-2025-preparation`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    {
      url: `${baseUrl}/ncert-biology-solutions`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/second-chance-neet`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/biology-notes`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/biology-coaching-near-me`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    // NEET Biology Coaching Hub Page - CRITICAL
    {
      url: `${baseUrl}/neet-biology-coaching`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.95,
    },
    // Course Sub-Pages
    {
      url: `${baseUrl}/courses/class-9-foundation`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/courses/class-10-foundation`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/courses/class-11`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/courses/class-12`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/courses/dropper`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/courses/foundation`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/courses/intensive-neet-biology`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/courses/neet-complete`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/courses/neet-dropper`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.85,
    },
    {
      url: `${baseUrl}/courses/compare`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/courses/finder`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.8,
    },
    // Company Pages
    {
      url: `${baseUrl}/company/careers`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.6,
    },
    {
      url: `${baseUrl}/company/results`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    // Services Sub-Pages
    {
      url: `${baseUrl}/services/classroom`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    {
      url: `${baseUrl}/services/doubt-resolution`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    {
      url: `${baseUrl}/services/international`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    {
      url: `${baseUrl}/services/online-classes`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    // Support Pages
    {
      url: `${baseUrl}/support/admission`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.6,
    },
    {
      url: `${baseUrl}/support/brochure`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.6,
    },
    {
      url: `${baseUrl}/support/demo`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    {
      url: `${baseUrl}/support/fees`,
      lastModified: lastUpdated,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    },
    // Test Platform
    {
      url: `${baseUrl}/tests`,
      lastModified: lastUpdated,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    // Thank You Page
    {
      url: `${baseUrl}/thank-you`,
      lastModified: lastUpdated,
      changeFrequency: 'yearly' as const,
      priority: 0.3,
    },
  ]

  return routes
}
