import { Lead, StageConfig } from './types'

export const stageConfigs: StageConfig[] = [
  {
    id: 'new_lead',
    name: 'New Leads',
    color: '#3B82F6',
    bgColor: '#EFF6FF',
    borderColor: '#93C5FD',
  },
  {
    id: 'demo_scheduled',
    name: 'Demo Scheduled',
    color: '#8B5CF6',
    bgColor: '#F5F3FF',
    borderColor: '#C4B5FD',
  },
  {
    id: 'demo_completed',
    name: 'Demo Completed',
    color: '#F59E0B',
    bgColor: '#FEF3C7',
    borderColor: '#FCD34D',
  },
  {
    id: 'offer_sent',
    name: 'Offer Sent',
    color: '#EC4899',
    bgColor: '#FCE7F3',
    borderColor: '#F9A8D4',
  },
  {
    id: 'payment_plan_created',
    name: 'Payment Plan Created',
    color: '#10B981',
    bgColor: '#D1FAE5',
    borderColor: '#6EE7B7',
  },
]

export const sampleLeads: Lead[] = [
  {
    id: '1',
    name: 'Priya Sharma',
    phone: '+91 98765 43210',
    email: 'priya.sharma@email.com',
    course: 'NEET Dropper 2025',
    priority: 'hot',
    stage: 'new_lead',
    lastContact: '2 hours ago',
    nextFollowUp: 'Today 3:00 PM',
    source: 'Website Demo Booking',
  },
  {
    id: '2',
    name: 'Rohan Kumar',
    phone: '+91 87654 32109',
    email: 'rohan.k@email.com',
    course: 'Class 12th Biology',
    priority: 'warm',
    stage: 'demo_scheduled',
    lastContact: '1 day ago',
    nextFollowUp: 'Tomorrow 11:00 AM',
    source: 'Instagram Ad',
  },
  {
    id: '3',
    name: 'Ananya Patel',
    phone: '+91 98761 23456',
    email: 'ananya.patel@email.com',
    course: 'NEET Dropper 2025',
    priority: 'hot',
    stage: 'new_lead',
    lastContact: '3 hours ago',
    nextFollowUp: 'Today 5:00 PM',
    source: 'Facebook Lead Ad',
  },
  {
    id: '4',
    name: 'Arjun Singh',
    phone: '+91 99998 88877',
    email: 'arjun.singh@email.com',
    course: 'Class 11th Biology',
    priority: 'warm',
    stage: 'new_lead',
    lastContact: '5 hours ago',
    nextFollowUp: 'Tomorrow 10:00 AM',
    source: 'Google Search',
  },
  {
    id: '5',
    name: 'Kavya Reddy',
    phone: '+91 91234 56789',
    email: 'kavya.reddy@email.com',
    course: 'NEET Dropper 2025',
    priority: 'hot',
    stage: 'demo_scheduled',
    lastContact: '2 days ago',
    nextFollowUp: 'Today 2:00 PM',
    source: 'Referral',
  },
  {
    id: '6',
    name: 'Aditya Verma',
    phone: '+91 98888 77776',
    email: 'aditya.v@email.com',
    course: 'Class 12th Biology',
    priority: 'cold',
    stage: 'new_lead',
    lastContact: '1 week ago',
    nextFollowUp: 'Next week',
    source: 'YouTube Ad',
  },
  {
    id: '7',
    name: 'Ishita Gupta',
    phone: '+91 97777 66665',
    email: 'ishita.gupta@email.com',
    course: 'NEET Dropper 2025',
    priority: 'hot',
    stage: 'new_lead',
    lastContact: '1 hour ago',
    nextFollowUp: 'Today 4:30 PM',
    source: 'Website Demo Booking',
  },
  {
    id: '8',
    name: 'Siddharth Joshi',
    phone: '+91 96666 55554',
    email: 'siddharth.j@email.com',
    course: 'Class 11th Biology',
    priority: 'warm',
    stage: 'demo_scheduled',
    lastContact: '3 days ago',
    nextFollowUp: 'Today 6:00 PM',
    source: 'Instagram Story',
  },
  {
    id: '9',
    name: 'Meera Nair',
    phone: '+91 95555 44443',
    email: 'meera.nair@email.com',
    course: 'NEET Dropper 2025',
    priority: 'hot',
    stage: 'demo_completed',
    lastContact: '4 hours ago',
    nextFollowUp: 'Tomorrow 9:00 AM',
    source: 'Referral',
  },
  {
    id: '10',
    name: 'Rahul Mehta',
    phone: '+91 94444 33332',
    email: 'rahul.mehta@email.com',
    course: 'Class 12th Biology',
    priority: 'warm',
    stage: 'new_lead',
    lastContact: '2 days ago',
    nextFollowUp: 'Tomorrow 3:00 PM',
    source: 'Facebook Ad',
  },
  {
    id: '11',
    name: 'Tanvi Desai',
    phone: '+91 93333 22221',
    email: 'tanvi.desai@email.com',
    course: 'NEET Dropper 2025',
    priority: 'hot',
    stage: 'demo_completed',
    lastContact: '1 day ago',
    nextFollowUp: 'Today 1:00 PM',
    source: 'Website Demo Booking',
  },
  {
    id: '12',
    name: 'Karthik Rao',
    phone: '+91 92222 11110',
    email: 'karthik.rao@email.com',
    course: 'Class 11th Biology',
    priority: 'cold',
    stage: 'new_lead',
    lastContact: '5 days ago',
    nextFollowUp: 'Next week',
    source: 'Google Search',
  },
  {
    id: '13',
    name: 'Divya Krishnan',
    phone: '+91 91111 00009',
    email: 'divya.k@email.com',
    course: 'NEET Dropper 2025',
    priority: 'hot',
    stage: 'demo_scheduled',
    lastContact: '6 hours ago',
    nextFollowUp: 'Tomorrow 11:30 AM',
    source: 'Instagram Reel',
  },
  {
    id: '14',
    name: 'Vivek Bansal',
    phone: '+91 90000 99998',
    email: 'vivek.bansal@email.com',
    course: 'Class 12th Biology',
    priority: 'warm',
    stage: 'demo_completed',
    lastContact: '2 hours ago',
    nextFollowUp: 'Today 7:00 PM',
    source: 'YouTube Video',
  },
  {
    id: '15',
    name: 'Sneha Iyer',
    phone: '+91 89999 88887',
    email: 'sneha.iyer@email.com',
    course: 'NEET Dropper 2025',
    priority: 'hot',
    stage: 'offer_sent',
    lastContact: '3 hours ago',
    nextFollowUp: 'Today 8:00 PM',
    source: 'Referral',
  },
  {
    id: '16',
    name: 'Aman Kapoor',
    phone: '+91 88888 77776',
    email: 'aman.kapoor@email.com',
    course: 'Class 11th Biology',
    priority: 'warm',
    stage: 'new_lead',
    lastContact: '4 days ago',
    nextFollowUp: 'Tomorrow 2:00 PM',
    source: 'Facebook Page',
  },
  {
    id: '17',
    name: 'Pooja Pillai',
    phone: '+91 87777 66665',
    email: 'pooja.pillai@email.com',
    course: 'NEET Dropper 2025',
    priority: 'hot',
    stage: 'demo_completed',
    lastContact: '1 hour ago',
    nextFollowUp: 'Today 9:30 PM',
    source: 'Website Demo Booking',
  },
  {
    id: '18',
    name: 'Varun Malhotra',
    phone: '+91 86666 55554',
    email: 'varun.m@email.com',
    course: 'Class 12th Biology',
    priority: 'cold',
    stage: 'demo_scheduled',
    lastContact: '1 week ago',
    nextFollowUp: 'Next week Monday',
    source: 'Instagram Ad',
  },
  {
    id: '19',
    name: 'Riya Saxena',
    phone: '+91 85555 44443',
    email: 'riya.saxena@email.com',
    course: 'NEET Dropper 2025',
    priority: 'hot',
    stage: 'offer_sent',
    lastContact: '5 hours ago',
    nextFollowUp: 'Tomorrow 10:30 AM',
    source: 'Referral',
  },
  {
    id: '20',
    name: 'Nikhil Agarwal',
    phone: '+91 84444 33332',
    email: 'nikhil.agarwal@email.com',
    course: 'Class 11th Biology',
    priority: 'warm',
    stage: 'demo_completed',
    lastContact: '2 days ago',
    nextFollowUp: 'Tomorrow 4:00 PM',
    source: 'Google Ads',
  },
  {
    id: '21',
    name: 'Shruti Bhatt',
    phone: '+91 83333 22221',
    email: 'shruti.bhatt@email.com',
    course: 'NEET Dropper 2025',
    priority: 'hot',
    stage: 'payment_plan_created',
    lastContact: '1 day ago',
    nextFollowUp: 'Today 12:00 PM',
    source: 'Website Demo Booking',
  },
  {
    id: '22',
    name: 'Akash Pandey',
    phone: '+91 82222 11110',
    email: 'akash.pandey@email.com',
    course: 'Class 12th Biology',
    priority: 'warm',
    stage: 'new_lead',
    lastContact: '3 days ago',
    nextFollowUp: 'Tomorrow 5:00 PM',
    source: 'Facebook Lead Gen',
  },
  {
    id: '23',
    name: 'Nisha Menon',
    phone: '+91 81111 00009',
    email: 'nisha.menon@email.com',
    course: 'NEET Dropper 2025',
    priority: 'hot',
    stage: 'demo_completed',
    lastContact: '4 hours ago',
    nextFollowUp: 'Today 6:30 PM',
    source: 'YouTube Ad',
  },
  {
    id: '24',
    name: 'Sameer Chopra',
    phone: '+91 80000 99998',
    email: 'sameer.chopra@email.com',
    course: 'Class 11th Biology',
    priority: 'cold',
    stage: 'offer_sent',
    lastContact: '6 days ago',
    nextFollowUp: 'Next week',
    source: 'Instagram Story',
  },
  {
    id: '25',
    name: 'Anjali Yadav',
    phone: '+91 79999 88887',
    email: 'anjali.yadav@email.com',
    course: 'NEET Dropper 2025',
    priority: 'hot',
    stage: 'payment_plan_created',
    lastContact: '2 hours ago',
    nextFollowUp: 'Tomorrow 1:00 PM',
    source: 'Referral',
  },
  {
    id: '26',
    name: 'Gaurav Sinha',
    phone: '+91 78888 77776',
    email: 'gaurav.sinha@email.com',
    course: 'Class 12th Biology',
    priority: 'warm',
    stage: 'demo_scheduled',
    lastContact: '1 day ago',
    nextFollowUp: 'Today 4:00 PM',
    source: 'Google Search',
  },
  {
    id: '27',
    name: 'Neha Bose',
    phone: '+91 77777 66665',
    email: 'neha.bose@email.com',
    course: 'NEET Dropper 2025',
    priority: 'hot',
    stage: 'payment_plan_created',
    lastContact: '3 hours ago',
    nextFollowUp: 'Today 11:00 AM',
    source: 'Website Demo Booking',
  },
  {
    id: '28',
    name: 'Harsh Trivedi',
    phone: '+91 76666 55554',
    email: 'harsh.trivedi@email.com',
    course: 'Class 11th Biology',
    priority: 'warm',
    stage: 'offer_sent',
    lastContact: '5 hours ago',
    nextFollowUp: 'Tomorrow 12:30 PM',
    source: 'Facebook Ad',
  },
  {
    id: '29',
    name: 'Priyanka Das',
    phone: '+91 75555 44443',
    email: 'priyanka.das@email.com',
    course: 'NEET Dropper 2025',
    priority: 'hot',
    stage: 'demo_completed',
    lastContact: '1 hour ago',
    nextFollowUp: 'Today 10:00 PM',
    source: 'Instagram Ad',
  },
  {
    id: '30',
    name: 'Vishal Jain',
    phone: '+91 74444 33332',
    email: 'vishal.jain@email.com',
    course: 'Class 12th Biology',
    priority: 'cold',
    stage: 'new_lead',
    lastContact: '1 week ago',
    nextFollowUp: 'Next week Tuesday',
    source: 'YouTube Channel',
  },
]
