import { PrismaClient } from '../src/generated/prisma/index.js'

const prisma = new PrismaClient()

const galleryItems = [
  {
    id: 'gal-001',
    type: 'PHOTO',
    url: '/images/gallery/img-2854.jpg',
    thumbnailUrl: '/images/gallery/img-2854.jpg',
    title: 'Dr. Shekhar Singh with Students',
    description: 'Cerebrum Biology Academy classroom session with AIIMS-trained faculty',
    category: 'FACULTY',
    tags: ['faculty', 'classroom', 'dr-shekhar'],
    featured: true,
    displayOrder: 1,
    aspectRatio: '4:3',
  },
  {
    id: 'gal-002',
    type: 'PHOTO',
    url: '/images/gallery/shekhar-sir-dean-south-city.png',
    thumbnailUrl: '/images/gallery/shekhar-sir-dean-south-city.png',
    title: 'Dr. Shekhar Singh - Dean Recognition at South City',
    description: 'Dr. Shekhar Singh recognized at South City International School',
    category: 'EVENTS',
    tags: ['recognition', 'school', 'south-city'],
    featured: true,
    displayOrder: 2,
    aspectRatio: '4:3',
  },
  {
    id: 'gal-003',
    type: 'PHOTO',
    url: '/images/gallery/shekhar-sir-welcome-mgr.png',
    thumbnailUrl: '/images/gallery/shekhar-sir-welcome-mgr.png',
    title: 'Welcome Ceremony at MGR School',
    description: 'Dr. Shekhar Singh welcomed at MGR School for NEET awareness seminar',
    category: 'SEMINARS',
    tags: ['seminar', 'school', 'welcome', 'mgr'],
    featured: false,
    displayOrder: 3,
    aspectRatio: '4:3',
  },
  {
    id: 'gal-004',
    type: 'PHOTO',
    url: '/images/gallery/teachers-day-mgr.png',
    thumbnailUrl: '/images/gallery/teachers-day-mgr.png',
    title: "Teachers' Day Celebration",
    description: "Celebrating Teachers' Day with school faculty and NEET aspirants at MGR",
    category: 'EVENTS',
    tags: ['teachers-day', 'celebration', 'mgr'],
    featured: true,
    displayOrder: 4,
    aspectRatio: '4:3',
  },
  {
    id: 'gal-005',
    type: 'PHOTO',
    url: '/images/gallery/untitled-design-5.png',
    thumbnailUrl: '/images/gallery/untitled-design-5.png',
    title: 'NEET Biology Workshop',
    description: 'Interactive Biology workshop for NEET aspirants',
    category: 'SEMINARS',
    tags: ['workshop', 'biology', 'neet'],
    featured: false,
    displayOrder: 5,
    aspectRatio: '4:3',
  },
  {
    id: 'gal-006',
    type: 'PHOTO',
    url: '/images/gallery/untitled-design-7.png',
    thumbnailUrl: '/images/gallery/untitled-design-7.png',
    title: 'NEET Topper Felicitation',
    description: 'Celebrating NEET toppers and their outstanding scores',
    category: 'TOPPERS',
    tags: ['toppers', 'achievement', 'felicitation'],
    featured: true,
    displayOrder: 6,
    aspectRatio: '4:3',
  },
  {
    id: 'gal-007',
    type: 'PHOTO',
    url: '/images/gallery/untitled-design-8.png',
    thumbnailUrl: '/images/gallery/untitled-design-8.png',
    title: 'Campus Life at Cerebrum',
    description: 'Students during a Biology practical session at our center',
    category: 'CAMPUS',
    tags: ['campus', 'practical', 'students'],
    featured: false,
    displayOrder: 7,
    aspectRatio: '4:3',
  },
  {
    id: 'gal-008',
    type: 'PHOTO',
    url: '/images/gallery/untitled-design-9.png',
    thumbnailUrl: '/images/gallery/untitled-design-9.png',
    title: 'NEET Counseling Session',
    description: 'One-on-one NEET guidance session with parents and students',
    category: 'SEMINARS',
    tags: ['counseling', 'parents', 'guidance'],
    featured: false,
    displayOrder: 8,
    aspectRatio: '4:3',
  },
  {
    id: 'gal-009',
    type: 'PHOTO',
    url: '/images/gallery/untitled-design-10.png',
    thumbnailUrl: '/images/gallery/untitled-design-10.png',
    title: 'Biology Lab Session',
    description: 'Hands-on Biology lab for NEET preparation',
    category: 'CAMPUS',
    tags: ['lab', 'biology', 'practical'],
    featured: false,
    displayOrder: 9,
    aspectRatio: '4:3',
  },
  {
    id: 'gal-010',
    type: 'PHOTO',
    url: '/images/gallery/untitled-design-11.png',
    thumbnailUrl: '/images/gallery/untitled-design-11.png',
    title: 'NEET Success Stories',
    description: 'Our students who made it to top medical colleges across India',
    category: 'TOPPERS',
    tags: ['success', 'medical-college', 'results'],
    featured: true,
    displayOrder: 10,
    aspectRatio: '4:3',
  },
  {
    id: 'gal-011',
    type: 'PHOTO',
    url: '/images/gallery/untitled-design-14.png',
    thumbnailUrl: '/images/gallery/untitled-design-14.png',
    title: 'Parent-Teacher Meeting',
    description: 'Regular PTM sessions to discuss student progress and NEET strategy',
    category: 'EVENTS',
    tags: ['ptm', 'parents', 'meeting'],
    featured: false,
    displayOrder: 11,
    aspectRatio: '4:3',
  },
  {
    id: 'gal-012',
    type: 'PHOTO',
    url: '/images/gallery/untitled-design-15.png',
    thumbnailUrl: '/images/gallery/untitled-design-15.png',
    title: 'NEET Awareness Drive',
    description: 'School outreach program for NEET awareness in Delhi NCR',
    category: 'SEMINARS',
    tags: ['awareness', 'outreach', 'delhi-ncr'],
    featured: false,
    displayOrder: 12,
    aspectRatio: '4:3',
  },
  {
    id: 'gal-013',
    type: 'PHOTO',
    url: '/images/gallery/untitled-design-16.png',
    thumbnailUrl: '/images/gallery/untitled-design-16.png',
    title: 'Faculty Development Workshop',
    description: 'Continuous faculty training at Cerebrum Biology Academy',
    category: 'FACULTY',
    tags: ['faculty', 'training', 'development'],
    featured: false,
    displayOrder: 13,
    aspectRatio: '4:3',
  },
  {
    id: 'gal-014',
    type: 'PHOTO',
    url: '/images/gallery/untitled-design-17.png',
    thumbnailUrl: '/images/gallery/untitled-design-17.png',
    title: 'Modern Study Center',
    description: 'State-of-the-art study facilities for NEET aspirants',
    category: 'CAMPUS',
    tags: ['campus', 'facilities', 'study-center'],
    featured: false,
    displayOrder: 14,
    aspectRatio: '4:3',
  },
  {
    id: 'gal-015',
    type: 'PHOTO',
    url: '/images/gallery/untitled-design-18.png',
    thumbnailUrl: '/images/gallery/untitled-design-18.png',
    title: 'Student Orientation Day',
    description: 'New batch orientation with course roadmap introduction',
    category: 'EVENTS',
    tags: ['orientation', 'new-batch', 'welcome'],
    featured: false,
    displayOrder: 15,
    aspectRatio: '4:3',
  },
  {
    id: 'gal-016',
    type: 'PHOTO',
    url: '/images/gallery/warm-welcome-by-mgr-staff.png',
    thumbnailUrl: '/images/gallery/warm-welcome-by-mgr-staff.png',
    title: 'Warm Welcome by MGR Staff',
    description: 'Cerebrum team welcomed for school NEET seminar at MGR',
    category: 'SEMINARS',
    tags: ['welcome', 'school', 'mgr'],
    featured: false,
    displayOrder: 16,
    aspectRatio: '4:3',
  },
  {
    id: 'gal-017',
    type: 'PHOTO',
    url: '/images/gallery/warm-welcome-by-mgr-staff-1.png',
    thumbnailUrl: '/images/gallery/warm-welcome-by-mgr-staff-1.png',
    title: 'NEET Guidance at MGR School',
    description: 'Expert guidance session for NEET Biology preparation',
    category: 'SEMINARS',
    tags: ['guidance', 'neet-prep', 'mgr'],
    featured: false,
    displayOrder: 17,
    aspectRatio: '4:3',
  },
]

async function seed() {
  console.log('Seeding gallery_items...')

  for (const item of galleryItems) {
    await prisma.gallery_items.upsert({
      where: { id: item.id },
      update: {
        url: item.url,
        thumbnailUrl: item.thumbnailUrl,
        title: item.title,
        description: item.description,
        category: item.category,
        tags: item.tags,
        featured: item.featured,
        displayOrder: item.displayOrder,
        aspectRatio: item.aspectRatio,
      },
      create: item,
    })
    console.log(`  ✓ ${item.title}`)
  }

  console.log(`\nDone! Seeded ${galleryItems.length} gallery items.`)
}

seed()
  .catch((e) => {
    console.error('Seed failed:', e)
    process.exit(1)
  })
  .finally(() => prisma.$disconnect())
